- docs/Theming.md
It's a start.
(related to #32)
> docs: add guide to theming 

- routes/_actions/addInstance.js
TODO: write some tests.
(related to https://github.com/nolanlawson/pinafore/issues/31)
> Fix #31: allow trailing slash in instance name

- docs/Theming.md
> docs: fix typo

- routes/_utils/ajax.js
> increase fetch timeout to 60 seconds for now

- routes/_components/LazyImage.html
- routes/_components/NonAutoplayGifv.html
- routes/_components/NonAutoplayImg.html
- routes/_components/dialog/components/ImageDialog.html
- routes/_components/status/Media.html
- tests/spec/109-compose-media.js
> Add img title as well as alt

- routes/_utils/smoothScrollToTop.js
> allow scroll-to-top to be canceled by a user scroll

- routes/_components/compose/ComposeBox.html
- routes/_components/compose/ComposeInput.html
> send status on ctrl+enter

- routes/_static/themes.js
- scss/themes/_offline.scss
- scss/themes/cobalt.scss
- templates/2xx.html
> add cobalt blue theme

- routes/_actions/accounts.js
- routes/_actions/follow.js
- routes/_components/profile/AccountProfileFollow.html
- routes/_pages/accounts/[accountId].html
> fix optimistic follow button

- routes/_actions/contentWarnings.js
- tests/spec/110-compose-content-warnings.js
- tests/utils.js
> Fix spoilers being posted after removal

- routes/_components/pseudoVirtualList/PseudoVirtualList.html
Possible fix for #92. Not sure though because it seems inconsistent, hard to repro.
> Simplify PseudoVirtualList

- routes/_utils/autosize.js
> Fix scrollTop jiggle in Firefox

- routes/_components/dialog/components/ModalDialog.html
> fix blurry modal dialog on chrome/safari

- routes/_components/IconButton.html
- routes/_components/compose/ComposeToolbar.html
> Fix spinner button spinning background

- routes/_components/status/Status.html
- routes/_components/status/StatusContent.html
- tests/spec/110-compose-content-warnings.js
> preload content in CW

- routes/_actions/addStatusOrNotification.js
> fix excessive itemIdsToAdd updates

- package.json
- routes/_components/status/StatusContent.html
- routes/_components/status/StatusSpoiler.html
- routes/_utils/emojifyText.js
- tests/spec/110-compose-content-warnings.js
> content warnings can have emoji

- routes/_actions/block.js
- routes/_api/block.js
- routes/_components/IconButton.html
- routes/_components/dialog/components/AccountProfileOptionsDialog.html
- routes/_components/dialog/components/StatusOptionsDialog.html
- routes/_components/dialog/creators/showAccountProfileOptionsDialog.js
- routes/_components/profile/AccountProfile.html
- routes/_components/profile/AccountProfileDetails.html
- routes/_components/profile/AccountProfileFollow.html
- routes/_components/profile/AccountProfileHeader.html
- tests/spec/113-block-unblock.js
- tests/utils.js
One of the many features listed in #6
> Block and unblock an account

- package-lock.json
- package.json
- server.js
> use full helmet() middleware

- routes/_components/profile/AccountProfileDetails.html
- routes/_components/profile/AccountProfileFollow.html
> hide overflow menu for same-user profile

- routes/_store/observers/onlineObservers.js
> only show "you are offline" notification once

- server.js
> disable CSP for /report.html

- templates/2xx.html
> update site meta description

- routes/_components/status/StatusDetails.html
- tests/spec/011-reblog-favorites-count.js
> fix favorites/boosts reversed aria labels

- routes/_actions/emoji.js
- tests/spec/018-compose-autosuggest.js
> fix autosuggestion mixed with emoji

- package.json
> redirect from www.pinafore.social to pinafore.social

- routes/_store/LocalStorageStore.js
Backstory: https://github.com/sveltejs/svelte/pull/1344
> remove deprecated store.onchange

- tests/spec/114-mute-unmute.js
I don't understand how this was ever passing.
> fix mute test

- routes/_store/observers/notificationObservers.js
> fix favicon logic

- routes/_components/AutoplayVideo.html
- routes/_components/dialog/components/ImageDialog.html
Slight modification to #171 with nitpicks addressed
> constrain gif backgrounds (with modifications)

- routes/_utils/scheduleIdleTask.js
> fix requestIdleCallback not defined in Edge

- routes/_components/IconButton.html
- routes/_store/LocalStorageStore.js
- routes/_store/mixins/timelineMixins.js
- routes/_utils/RealmStore.js
> fix animations and cleanup store/component get() usage

- server.js
> add Referrer-Policy: no-referrer

- routes/_components/compose/ComposeAutosuggest.html
- routes/_components/compose/ComposeInput.html
- tests/spec/018-compose-autosuggest.js
> fix multiple compose autosuggest dropdowns

- webpack.client.config.js
This seems to result in better webpack chunks but needs verification
> use chunks:all in webpack splitChunks

- routes/_components/status/Status.html
This reduces the bundle size of Status.html from 31.63kB to 29.03kB while also making the code simpler and easier to read.
> simplify Status.html using spread params

- routes/_utils/scheduleIdleTask.js
> fix requestIdleCallback in edge/safari

- routes/_components/timeline/Timeline.html
- routes/_utils/asyncModules.js
this should cut off 10-15kB from loading the home feed
> make timeline components async

- tests/roles.js
- tests/spec/002-login-spec.js
- tests/utils.js
pressing the 'enter' button seems really flaky, fails sometimes for apparent timing reasons. let's just click the button
> fix flaky login tests

- routes/_api/followsAndFollowers.js
- routes/_components/profile/AccountProfileDetails.html
- routes/_pages/accounts/[accountId]/followers.html
- routes/_pages/accounts/[accountId]/follows.html
- routes/accounts/[accountId]/followers.html
- routes/accounts/[accountId]/follows.html
- tests/spec/021-followers-follows.js
- tests/utils.js
This adds some small tweaks to #214:
- hovered links aren't underlined
- flex direction is vertical on mobile to save space
- adds a test
> Follows and followers (updated)

- bin/restore-mastodon-data.js
- routes/_actions/pin.js
- routes/_api/pin.js
- routes/_api/statuses.js
- routes/_components/dialog/components/StatusOptionsDialog.html
- routes/_components/dialog/creators/showStatusOptionsDialog.js
- routes/_components/status/StatusToolbar.html
- routes/_components/timeline/PinnedStatuses.html
- routes/_database/timelines/pinnedStatuses.js
- routes/_database/timelines/updateStatus.js
- tests/spec/004-pinned-statuses.js
- tests/spec/116-follow-requests.js
- tests/spec/117-pin-unpin.js
- tests/utils.js
> add ability to pin and unpin statuses

- routes/_components/Avatar.html
- routes/_components/NonAutoplayImg.html
Once the avatar is loaded, get rid of the gray background.
Fixes #233
> avatar should not have gray background

- routes/_components/compose/ComposeAutosuggest.html
- routes/_components/compose/ComposeLengthIndicator.html
- routes/_components/pseudoVirtualList/PseudoVirtualListLazyItem.html
- routes/_components/timeline/Timeline.html
- routes/_components/virtualList/VirtualListLazyItem.html
I've seen this occasionally during testing
> fix null error in virtual list items

- routes/_components/status/Notification.html
> fix for malformed notifications

- routes/_components/Avatar.html
- routes/_components/DynamicPageBanner.html
- routes/_components/ExternalLink.html
- routes/_components/IconButton.html
- routes/_components/LazyImage.html
- routes/_components/LoadingPage.html
- routes/_components/LoadingSpinner.html
- routes/_components/compose/ComposeAutosuggest.html
- routes/_components/compose/ComposeBox.html
- routes/_components/compose/ComposeLengthGauge.html
- routes/_components/compose/ComposeLengthIndicator.html
- routes/_components/pseudoVirtualList/PseudoVirtualList.html
- routes/_components/pseudoVirtualList/PseudoVirtualListItem.html
- routes/_components/pseudoVirtualList/PseudoVirtualListLazyItem.html
- routes/_components/status/Media.html
- routes/_components/status/Status.html
- routes/_components/timeline/LazyTimeline.html
- routes/_components/timeline/Timeline.html
- routes/_components/virtualList/VirtualListHeader.html
- routes/_components/virtualList/VirtualListLazyItem.html
- routes/_pages/settings/instances/[instanceName].html
- routes/_utils/events.js
- webpack.client.config.js
It seems that compatibility with Svelte 2.0 is going to be a multi-step process. We're too far away to do it all at once.
This gets us a little bit closer.
> slightly improve Svelte 2.0 compatibility

- routes/_components/Layout.html
- routes/_components/Nav.html
- routes/_components/NavItem.html
- routes/_store/computations/computations.js
- routes/_store/computations/instanceComputations.js
- routes/_store/computations/navComputations.js
- routes/_store/observers/navObservers.js
- routes/_store/observers/observers.js
Adds a superfluous little animation to the nav bar to accentuate the navigation from page to page.
> add animation for navigation bar indicator

- routes/_components/compose/ComposeAutosuggest.html
- routes/_components/compose/ComposeLengthGauge.html
- routes/_components/compose/ComposeLengthIndicator.html
- routes/_components/pseudoVirtualList/PseudoVirtualListItem.html
- routes/_components/pseudoVirtualList/PseudoVirtualListLazyItem.html
- routes/_components/timeline/Timeline.html
- routes/_components/virtualList/VirtualListLazyItem.html
https://github.com/sveltejs/svelte/issues/1354 is fixed now
> remove unnecessary sveltejs/svelte#1354 workarounds

- routes/_actions/autosuggest.js
- routes/_actions/compose.js
- routes/_actions/emoji.js
- routes/_components/compose/ComposeAutosuggest.html
- routes/_components/compose/ComposeAutosuggestionList.html
- routes/_components/compose/ComposeInput.html
- routes/_store/computations/autosuggestComputations.js
- routes/_store/computations/computations.js
- routes/_store/mixins/autosuggestMixins.js
- routes/_store/mixins/mixins.js
- routes/_store/observers/autosuggestObservers.js
- routes/_store/observers/observers.js
- webpack.client.config.js
> isolate autosuggestion state

- routes/_components/virtualList/virtualListStore.js
This code is not supposed to be exposed in production.
> wrap code in dev block

- routes/_components/dialog/components/StatusOptionsDialog.html
> only allow public/unlisted statuses to be pinned

- routes/_actions/muteConversation.js
- routes/_api/muteConversation.js
- routes/_components/dialog/components/StatusOptionsDialog.html
- routes/_database/timelines/updateStatus.js
> add ability to mute conversation

- .travis.yml
I don't think this is necessary.
> travis: remove gstreamer package

- package-lock.json
I have no idea why we have to keep doing this. I assume it's because npm versions are inconsistent between Travis and my local dev environment?
> update package-lock.json again for some reason

- Dockerfile
- README.md
- server.js
Note: A running Docker container must be killed instead of getting stopped. Ctrl-C/`SIGINT` doesn't seem to work while running Pinafore.
> Added Dockerfile

- .travis.yml
- package.json
> run node 10 in both travis and now

- package-lock.json
- package.json
> fix(package): update events to version 3.0.0

- package-lock.json
- package.json
> fix(package): update webpack to version 4.10.2

- .travis.yml
I'm tired of builds constantly failing over this
> use npm install instead of npm ci in travis

- tests/spec/003-basic-timeline-spec.js
I hope this will improve flakiness but TBH I have no idea.
> tests: improve flakiness in basic timeline spec

- tests/utils.js
I suspect these are another source of test flakiness
> remove .find()s from testcafe in utils.js

- tests/spec/005-status-types.js
- tests/spec/008-status-media.js
- tests/spec/010-focus.js
- tests/spec/016-external-links.js
- tests/spec/021-followers-follows.js
- tests/spec/102-notifications.js
- tests/spec/108-compose-dialog.js
- tests/spec/110-compose-content-warnings.js
- tests/spec/111-focus.js
- tests/spec/112-status-links.js
maybe this will make tests less flaky
> remove more testcafe .find() calls

- routes/_components/status/StatusHeader.html
- tests/utils.js
> Fix text overflow on status headers

- routes/_actions/followRequests.js
- routes/_api/block.js
- routes/_api/blockedAndMuted.js
- routes/_api/delete.js
- routes/_api/emoji.js
- routes/_api/favorite.js
- routes/_api/follow.js
- routes/_api/followsAndFollowers.js
- routes/_api/instance.js
- routes/_api/lists.js
- routes/_api/media.js
- routes/_api/mute.js
- routes/_api/muteConversation.js
- routes/_api/oauth.js
- routes/_api/pin.js
- routes/_api/pinnedStatuses.js
- routes/_api/reblogsAndFavs.js
- routes/_api/requests.js
- routes/_api/search.js
- routes/_api/statuses.js
- routes/_api/timelines.js
- routes/_api/user.js
- routes/_utils/ajax.js
> add more fine-grained request timeouts

- routes/_components/status/Status.html
- routes/_components/status/StatusMentions.html
> add mentions outside of content warnings

- routes/_components/status/StatusMentions.html
> status mentions should use short usernames

- routes/_components/status/StatusMentions.html
> short mentions should have full title

- docs/Admin-Guide.md
This may help instance admins who are having trouble with Pinafore compat.
> Add instructions for admins to achieve Pinafore compatibility

- README.md
> Add more admin notes

- routes/_components/dialog/components/AccountProfileOptionsDialog.html
- routes/_components/dialog/components/GenericDialogList.html
- routes/_components/dialog/components/PostPrivacyDialog.html
- routes/_components/dialog/components/StatusOptionsDialog.html
> fix overflow inside of modals

- routes/_components/compose/ComposeMediaItem.html
> fix media alt input color on dark theme

- routes/_components/status/StatusMentions.html
> make mentions the same size when focused

- routes/_components/status/Status.html
- routes/_components/status/StatusContent.html
> fix statuses with empty content text

- routes/_components/compose/ComposeAuthor.html
- routes/_components/profile/AccountDisplayName.html
- routes/_components/profile/AccountProfileHeader.html
- routes/_components/status/Status.html
- routes/_utils/emojifyText.js
- routes/_utils/removeEmoji.js
- tests/spec/118-display-name-custom-emoji.js
improvements to #450 to fix #449, especially for aria labels
> better support for de-emojified user display names

- routes/_utils/removeEmoji.js
- tests/spec/118-display-name-custom-emoji.js
another follow-up to #450 to fix #449
> use better emoji removal algorithm

- routes/_components/profile/AccountProfileNote.html
- routes/_components/status/StatusContent.html
- routes/_utils/massageUserText.js
> allow custom emoji in user profiles

- routes/_components/Label.html
- routes/_components/profile/AccountProfile.html
- routes/_components/profile/AccountProfileHeader.html
> add label for bots

- templates/service-worker.js
> add null check for index.html fetch in SW

- routes/_actions/timeline.js
- routes/_api/statuses.js
- routes/_api/timelines.js
- routes/_utils/arrays.js
slight refactor in anticipation of improving performance of thread fetching
> slight refactor of timeline fetching

- routes/_components/compose/ComposeAutosuggestionList.html
> fix incorrect autocomplete avatars

- routes/_actions/accounts.js
- routes/_actions/follow.js
- routes/_actions/setShowReblogs.js
- routes/_api/relationships.js
- routes/_api/showReblogs.js
- routes/_api/user.js
- routes/_components/dialog/components/AccountProfileOptionsDialog.html
- routes/_database/accounts.js
- routes/_database/relationships.js
- routes/_store/observers/autosuggestObservers.js
> Add ability to show/hide boosts from accounts

- routes/_actions/accounts.js
- routes/_actions/setDomainBlocked.js
- routes/_api/blockDomain.js
- routes/_components/dialog/components/AccountProfileOptionsDialog.html
- routes/_components/profile/AccountProfileHeader.html
> add domain blocking

- routes/_actions/copyText.js
- routes/_components/dialog/components/AccountProfileOptionsDialog.html
- routes/_components/dialog/components/StatusOptionsDialog.html
this avoids an extra popup where available
> use async clipboard API

- routes/_actions/compose.js
- routes/_actions/media.js
- routes/_api/statuses.js
- routes/_components/compose/ComposeBox.html
- routes/_components/compose/ComposeMedia.html
- routes/_components/compose/ComposeMediaItem.html
- tests/spec/012-compose.js
- tests/spec/013-compose-media.js
- tests/spec/109-compose-media.js
> media uploads no longer add URLs to status text

- routes/_components/status/StatusDetails.html
it should not show "Web" by default but should be absent if `application` is null
> fix application name

- routes/_components/dialog/components/AccountProfileOptionsDialog.html
> fix null error in profile

- package-lock.json
- package.json
- routes/_actions/accounts.js
- routes/_actions/addInstance.js
- routes/_actions/addStatusOrNotification.js
- routes/_actions/compose.js
- routes/_actions/deleteStatuses.js
- routes/_actions/emoji.js
- routes/_actions/favorite.js
- routes/_actions/instances.js
- routes/_actions/lists.js
- routes/_actions/muteConversation.js
- routes/_actions/pin.js
- routes/_actions/pinnedStatuses.js
- routes/_actions/reblog.js
- routes/_actions/statuses.js
- routes/_actions/timeline.js
- routes/_components/timeline/Timeline.html
- routes/_database/accounts.js
- routes/_database/cache.js
- routes/_database/cleanup.js
- routes/_database/database.dev.js
- routes/_database/database.js
- routes/_database/databaseLifecycle.js
- routes/_database/databaseWorker.js
- routes/_database/knownInstances.js
- routes/_database/timelines/pagination.js
- routes/_store/observers/autosuggestObservers.js
- routes/_utils/marks.js
- webpack.client.config.js
This is just an experiment, needs validation to make sure it's actually a perf improvement
> run indexeddb operations in a web worker

- routes/_components/LazyImage.html
- routes/_components/NonAutoplayImg.html
- routes/_utils/decodeImage.js
This avoids the janky-looking flash of unloaded images
> fix image loading

- routes/_database/databaseLifecycle.js
- routes/_utils/asyncModules.js
- routes/_utils/loadPolyfills.js
> fix idb getall in edge

- webpack.client.config.js
> fix safari10 uglify issue

- inline-script.js
- routes/_pages/settings/instances/[instanceName].html
- routes/_static/themes.js
Should be much easier to figure out what themes look like now
> add a theme preview

- routes/_components/settings/instance/InstanceActions.html
- routes/_components/settings/instance/InstanceUserProfile.html
- routes/_components/settings/instance/PushNotificationSettings.html
- routes/_components/settings/instance/ThemeSettings.html
- routes/_pages/settings/instances/[instanceName].html
The "instance settings" screen was getting a little hairy, so I broke it up into multiple small components.
> refactor instance settings

- routes/_pages/settings/general.html
- routes/_pages/settings/instances/index.html
When I wanted to change the theme, the page 'Settings > General' was the first place I looked  
Not managing to find it, I went on a search throughout various issues and PRs (#46  , for
example) before locating it.
Now I hope to spare others the search
> Provide directions to change the theme

- routes/_pages/settings/general.html
- routes/_pages/settings/instances/index.html
As mentioned in #585, I would like to tweak the way that the theme settings are hinted at.
> Slight changes to theme settings hint

- routes/_store/observers/notificationPermissionObservers.js
> fix: fix null reference error in Safari/Edge

- .travis.yml
- bin/setup-mastodon-in-travis.sh
per https://travis-ci.community/t/trusty-environment-redis-server-not-starting-with-redis-tools-installed/650/2
> fix redis issue in travis without building redis from source

- routes/_components/Title.html
- routes/accounts/[accountId].html
- routes/accounts/[accountId]/followers.html
- routes/accounts/[accountId]/follows.html
- routes/blocked.html
- routes/community/index.html
- routes/favorites.html
- routes/federated.html
- routes/index.html
- routes/lists/[listId].html
- routes/local.html
- routes/muted.html
- routes/notifications.html
- routes/pinned.html
- routes/requests.html
- routes/search.html
- routes/settings/about.html
- routes/settings/general.html
- routes/settings/index.html
- routes/settings/instances/[instanceName].html
- routes/settings/instances/add.html
- routes/settings/instances/index.html
- routes/statuses/[statusId]/favorites.html
- routes/statuses/[statusId]/index.html
- routes/statuses/[statusId]/reblogs.html
- routes/tags/[tagName].html
- tests/spec/102-notifications.js
- tests/utils.js
> feat(title): add dynamic document title

- routes/_pages/settings/instances/add.html
> fix(design): input bg should be white on "add instance" page

- routes/_utils/replaceEmoji.js
- tests/unit/test-emoji.js
> fix(emoji): emoji replacer should ignore pound sign

- package-lock.json
- routes/_utils/replaceEmoji.js
- tests/unit/test-emoji.js
There are apparently a lot of "emoji" that aren't really emoji.
> fix(emoji): asterisk should not be treated as emoji

- routes/_utils/replaceEmoji.js
- tests/unit/test-emoji.js
> fix(emoji): fix ™® characters treated as emoji

- scss/themes/_base.scss
- scss/themes/_dark.scss
- scss/themes/_dark_scrollbars.scss
- scss/themes/_default.scss
- scss/themes/_light_scrollbars.scss
- scss/themes/_offline.scss
- scss/themes/cobalt.scss
- scss/themes/gecko.scss
- scss/themes/hacker.scss
- scss/themes/hotpants.scss
- scss/themes/majesty.scss
- scss/themes/oaken.scss
- scss/themes/ozark.scss
- scss/themes/punk.scss
- scss/themes/riot.scss
- scss/themes/scarlet.scss
- scss/themes/seafoam.scss
- scss/themes/sorcery.scss
I wanted Sorcery to not be quite so bright, so I refactored this SCSS a bit.
> fix(design): tweak scrollbar colors

- routes/_utils/replaceEmoji.js
- tests/unit/test-emoji.js
Found another case where #679 occurs, this should fix it.
> actualy fix trademark character

- routes/_store/store.js
> fix(a11y): default "prefers reduced motion" to OS/browser default

- bin/restore-mastodon-data.js
- routes/_a11y/getAccessibleLabelForStatus.js
- routes/_components/status/StatusContent.html
- tests/serverActions.js
- tests/spec/118-display-name-custom-emoji.js
- tests/spec/120-status-aria-label.js
- tests/submitMedia.js
> fix(a11y): fix NVDA crash on long aria-label

- tests/spec/010-focus.js
This test is really flaky. Trying to make it less so.
> chore(tests): make focus test less flaky

- routes/_components/status/StatusMediaAttachments.html
- routes/_pages/settings/general.html
- routes/_store/store.js
- tests/spec/023-mark-media-as-sensitive.js
- tests/utils.js
fixes #699. I also went ahead and divided the settings into two groups: Preferences and Accessibility
> feat(ui): add option to always show sensitive media

- .editorconfig
borrowed from standardjs's github repo
> chore(editor): add an editorconfig

- routes/_components/compose/ComposeStickyButton.html
hopefully the final fix for #667 to make it actually work
> fix(iOS): fix faux-sticky button placement

- routes/_static/themes.js
- scss/themes/pitchblack.scss
- templates/2xx.html
This theme is made with mobile OLED screens (iPhone XS for instance). This is the reason I used a pure black background.
> Add the Pitch Black theme

- routes/_components/IconButton.html
- routes/_components/LazyImage.html
- routes/_components/NonAutoplayImg.html
- routes/_components/compose/ComposeInput.html
Invalid aria labels, missing label.
> fix(a11y): fix a11y issues caught by lighthouse

- routes/_actions/lists.js
- routes/_pages/community/index.html
- routes/_store/observers/instanceObservers.js
try to defer more work, split everything up into more functional code for easier reading
> fix(observers): refactor instance observers, minor optimizations

- routes/_actions/addInstance.js
This was supposed to show an error message
> fix: error msg when logging in to same instance

- routes/_components/AutoplayVideo.html
- routes/_components/LazyImage.html
- routes/_components/NonAutoplayGifv.html
- routes/_components/dialog/components/ImageDialog.html
- routes/_components/status/Media.html
- routes/_components/status/MediaAttachments.html
- routes/_components/status/StatusMediaAttachments.html
- routes/_pages/settings/general.html
- routes/_store/store.js
- routes/_utils/coordsToPercent.js
Per pull request comments in #747
> Modifications to #747

- routes/_components/Avatar.html
- routes/_components/DynamicPageBanner.html
- routes/_components/ExternalLink.html
- routes/_components/IconButton.html
- routes/_components/LoadingSpinner.html
- routes/_components/NavItem.html
- routes/_components/NotLoggedInHome.html
- routes/_components/PlayVideoIcon.html
- routes/_components/community/PageListItem.html
- routes/_components/compose/ComposeButton.html
- routes/_components/compose/ComposeMediaItem.html
- routes/_components/dialog/components/GenericDialogList.html
- routes/_components/dialog/components/ModalDialog.html
- routes/_components/search/Search.html
- routes/_components/settings/SettingsListItem.html
- routes/_components/status/StatusDetails.html
- routes/_components/status/StatusHeader.html
- routes/_components/status/StatusMediaAttachments.html
in #762 I forgot to set the absolute path for these; it fails on
subpages
> fix(icons): fix icons.svg url

- src/routes/_actions/addStatusOrNotification.js
- tests/spec/122-replies-in-thread.js
- tests/utils.js
> fix: fix duplicate statuses in threads

- src/routes/_components/NavItem.html
this seems to help mobile firefox on android especially
> perf: slightly improve framerate of navbar indicator

- src/routes/_pages/settings/instances/add.html
> fix: show warning when local storage is unavailable

- tests/spec/017-compose-reply.js
- tests/utils.js
This should fix test failures in #784 which somehow
exposed our flaky tests.
> fix: fix flaky test by clicking relative date

- scss/themes/_dark.scss
fixes #797
This feels much less jarring to me
> fix(style): use dark placeholder on dark theme

- package.json
`now` needs this to deploy correctly
> fix: fix "now" files for thirdparty

- bin/build-template-html.js
- package.json
The build process wasn't building the template file correctly in dev mode
> chore: fix build process in dev mode

- src/routes/_components/dialog/components/EmojiDialog.html
temporary fix until https://github.com/missive/emoji-mart/pull/256 is merged
> fix: fix appearance of native emoji on linux

- CONTRIBUTING.md
I figured it was about time I brain-dumped about how the project actually works and things to look out for, for the benefit of someone new contributing to the project.
> docs: add way more contributing docs

- src/routes/_actions/deleteAndRedraft.js
- src/routes/_components/dialog/components/StatusOptionsDialog.html
- src/routes/_utils/statusHtmlToPlainText.js
- tests/spec/121-delete-and-redraft.js
> fix: preserve newlines correctly in delete-and-redraft

- CONTRIBUTING.md
> docs: add some more contributing instructions

- src/routes/_components/NavShortcuts.html
- src/routes/_components/ShortcutHelpInfo.html
- tests/spec/024-shortcuts-navigation.js
Follow-up to #870 - 1-6 hotkeys switch columns
> feat: 1-6 hotkeys switch columns

- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusDetails.html
- src/routes/_components/status/StatusRelativeDate.html
- src/routes/_utils/formatters.js
> feat: date title shows absolute date

- src/routes/_utils/shortcuts.js
- tests/unit/test-shortcuts.js
> fix: fix Alt key in keyboard shortcuts

- src/routes/_components/status/Notification.html
- src/routes/_components/timeline/NotificationVirtualListItem.html
- tests/spec/025-shortcuts-status.js
> fix: fix keyboard shortcuts in notifications

- src/routes/_components/status/Status.html
- tests/spec/026-shortcuts-notification.js
> fix: fix notification m/p keyboard shortcuts

- .gitignore
- bin/build-inline-script.js
- bin/build-template-html.js
- src/inline-script/inline-script.js
- src/server.js
Source files should be in `src`
> chore: move inline-script to src

- src/routes/_utils/scrollIntoView.js
Hi !
I tried to address the remaining open comments on #870:
caching the main-nav element, in 59b13dc
I tried using binary search for firstVisibleElementIndex, but the result was actually slower than the straightforward implementation on Chrome :)  Virtual lists seem to have at most 20 items, so the size is limited.
However, while doing it, I noticed that the return value of firstVisibleElementIndex was wrong in the case where there was no visible elements, so I fixed it in b16406f
> Follow-up for pull request  #870

- src/routes/_components/dialog/components/CopyDialog.html
> fix: fix "copy link" on iOS

- src/inline-script/inline-script.js
- src/routes/_components/settings/SettingsListItem.html
- src/routes/_pages/settings/general.html
- src/routes/_store/observers/loggedInObservers.js
- src/routes/_store/observers/underlineLinksObservers.js
- src/routes/_store/store.js
- src/scss/global.scss
Disabled by default, as we already have good color contrast in the links.
> feat: add option to underline links in toot text

- src/routes/_components/IconButton.html
- src/routes/_components/dialog/components/MediaDialog.html
These buttons didn't have the right color when active.
> fix: fix pressed color on media dialog buttons

- src/routes/_components/ShortcutHelpInfo.html
- src/routes/_components/dialog/components/MediaDialog.html
Hey
I have no idea what I'm doing but seems to be working and I really want this :sweat_smile:
> Add shortcuts to the media dialog

- src/routes/_components/dialog/components/MediaDialog.html
> fix: fix zoomable videos

- src/routes/_components/settings/SettingsListButton.html
- src/routes/_pages/settings/instances/index.html
Fixes some small issues from https://github.com/nolanlawson/pinafore/pull/945
- add aria-pressed states, aria-label, and title for accessibility
- wrap the buttons in divs so the focus outline will always be visible
- some minor style changes for small mobile screens (e.g. iphone 4)
> fix: minor fixups for accessibility and responsive design

- src/routes/_components/Nav.html
> fix: fix items appearing over nav

- src/routes/_components/status/Status.html
> fix: fix hand cursor on non-tappable status

- src/routes/_components/IconButton.html
- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/PinchZoomable.html
Another dumb mistake I made, forgot to make invisible icons aria-hidden.
> fix: fix aria-hidden on hidden icons

- src/routes/_utils/smoothScroll.js
> fix: disable smooth scroll for users who prefer reduced motion

- src/inline-script/inline-script.js
- src/routes/_actions/addInstance.js
- src/routes/_actions/instances.js
- src/routes/_components/NotLoggedInHome.html
- src/routes/_components/settings/instance/ThemeSettings.html
- src/routes/_store/computations/instanceComputations.js
- src/routes/_utils/themeEngine.js
- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
fixes #728
New landing page if you're in dark mode:
> fix: set dark theme based on prefers-color-scheme

- src/routes/_components/settings/instance/ThemeSettings.html
- src/routes/_pages/settings/general.html
Also tweak some of the styles and layout in the theme picker itself
> fix: don't show theme picker if not logged in

- README.md
Just some minor readme changes
> docs: slightly refactor readme

- package.json
fixes a deploy bug introduced in #976
> chore: tell now about server.js

- src/scss/themes/_base.scss
this gets us up to 100% accessibility score on lighthouse
> fix: fix default contrast ratio for button

- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeFileDrop.html
- src/routes/_components/compose/ComposeInput.html
- src/routes/_components/compose/ComposeMedia.html
- src/routes/_components/compose/ComposeMediaItem.html
> fix: fix slim size compose dialog

- src/routes/_actions/showShareDialogIfNecessary.js
- src/routes/_pages/index.html
- src/routes/_store/observers/instanceObservers.js
- src/routes/_store/store.js
- src/routes/_utils/decodeURIComponentWithPluses.js
- src/routes/share.html
- static/manifest.json
- tests/spec/027-share-target.js
> feat: implement web share target

- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeFileDrop.html
- src/routes/_components/compose/ComposeInput.html
- src/routes/_components/compose/ComposeMedia.html
- src/routes/_components/compose/ComposeMediaItem.html
> fix: fix style of compose box in reply

- src/scss/themes/_base.scss
This makes the primary button match the border color of the nav bar, looks more consistent.
> fix: tweak primary button border color

- now.json
- package.json
more junk I am doing to try to address #985
> chore: pin to zeit v1 for the time being

- src/routes/_components/NavItem.html
- src/scss/themes/_base.scss
- src/scss/themes/_dark_navbar.scss
- src/scss/themes/hacker.scss
- src/scss/themes/punk.scss
- src/scss/themes/riot.scss
- src/scss/themes/sorcery.scss
Surprised I never added active states to the nav buttons, but this fixes that.
> fix: improve active state of navbar

- src/routes/_components/settings/instance/ThemeSettings.html
improve a11y of the theme picker by allowing you to tap on the little squares
> fix: improve a11y, move preview box inside label

- src/routes/_pages/community/index.html
another thing I missed in #1000 and #1002
> fix: add federated/favorites to crawled pages

- src/routes/_actions/mute.js
- src/routes/_actions/toggleMute.js
- src/routes/_api/mute.js
- src/routes/_components/dialog/asyncDialogs.js
- src/routes/_components/dialog/components/AccountProfileOptionsDialog.html
- src/routes/_components/dialog/components/GenericConfirmationDialog.html
- src/routes/_components/dialog/components/MuteDialog.html
- src/routes/_components/dialog/components/StatusOptionsDialog.html
- src/routes/_components/dialog/components/TextConfirmationDialog.html
- src/routes/_components/dialog/creators/showMuteDialog.js
- src/routes/_components/dialog/creators/showTextConfirmationDialog.js
- src/routes/_components/settings/instance/InstanceActions.html
- src/routes/_components/settings/instance/PushNotificationSettings.html
- src/routes/_pages/muted.html
- tests/spec/002-login-spec.js
- tests/spec/114-mute-unmute.js
- tests/utils.js
> feat: allow muting notifications when muting

- src/routes/_components/NavItem.html
- src/routes/_components/NavItemIcon.html
- src/routes/_store/computations/timelineComputations.js
Minor refactor, fixes a bug where the notification badge doesn't show if you're on the settings page or community page.
> fix: refactor NavItem, fix icon badge bug

- src/routes/_components/dialog/creators/showAccountProfileOptionsDialog.js
- src/routes/_components/dialog/creators/showComposeDialog.js
- src/routes/_components/dialog/creators/showCopyDialog.js
- src/routes/_components/dialog/creators/showDialog.js
- src/routes/_components/dialog/creators/showEmojiDialog.js
- src/routes/_components/dialog/creators/showMediaDialog.js
- src/routes/_components/dialog/creators/showMuteDialog.js
- src/routes/_components/dialog/creators/showPostPrivacyDialog.js
- src/routes/_components/dialog/creators/showShortcutHelpDialog.js
- src/routes/_components/dialog/creators/showStatusOptionsDialog.js
- src/routes/_components/dialog/creators/showTextConfirmationDialog.js
There was a lot of duplicated code here, it was starting to get tiresome.
> refactor: refactor dialogs

- bin/svgs.js
- src/routes/_actions/getRecentStatusesForAccount.js
- src/routes/_actions/report.js
- src/routes/_actions/reportStatuses.js
- src/routes/_api/report.js
- src/routes/_components/dialog/asyncDialogs.js
- src/routes/_components/dialog/components/AccountProfileOptionsDialog.html
- src/routes/_components/dialog/components/GenericConfirmationDialog.html
- src/routes/_components/dialog/components/GenericDialogList.html
- src/routes/_components/dialog/components/MuteDialog.html
- src/routes/_components/dialog/components/ReportDialog.html
- src/routes/_components/dialog/components/StatusOptionsDialog.html
- src/routes/_components/dialog/creators/showReportDialog.js
- tests/spec/028-report-ui.js
- tests/utils.js
fixes #736
I also went ahead and fixed a bunch of dialogs that open other dialogs. Turns out if I open them in the wrong order, the timeline underneath might be scrollable while the dialog is open, which we don't want.
> feat: report an account or toots

- src/routes/_components/list/ListItem.html
- src/routes/_components/list/listStore.js
- src/routes/_components/shortcut/ScrollListShortcuts.html
- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- src/routes/_components/timeline/NotificationVirtualListItem.html
- src/routes/_components/timeline/StatusVirtualListItem.html
- src/routes/_components/virtualList/VirtualList.html
- src/routes/_components/virtualList/VirtualListItem.html
- src/routes/_components/virtualList/virtualListStore.js
- tests/spec/024-shortcuts-navigation.js
- tests/spec/025-shortcuts-status.js
- tests/spec/026-shortcuts-notification.js
- tests/utils.js
> fix: j/k shortcuts correctly set active element

- bin/svgs.js
- src/routes/_components/Avatar.html
- src/routes/_components/profile/AccountProfile.html
- src/routes/_components/profile/AccountProfileHeader.html
- src/routes/_components/profile/AccountProfileMovedBanner.html
> feat: add "accout has moved" banner

- src/routes/_components/list/List.html
- src/routes/_components/shortcut/ScrollListShortcuts.html
- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusMediaAttachments.html
- src/routes/_components/status/StatusSpoiler.html
- src/routes/_components/status/StatusToolbar.html
- src/routes/_components/timeline/NotificationVirtualListItem.html
- src/routes/_components/timeline/PinnedStatuses.html
- src/routes/_components/timeline/StatusVirtualListItem.html
- src/routes/_components/timeline/Timeline.html
- src/routes/_components/virtualList/VirtualList.html
- src/routes/_utils/scrollIntoView.js
- tests/spec/010-focus.js
- tests/spec/025-shortcuts-status.js
- tests/spec/111-focus.js
- tests/utils.js
> fix: fix keyboard shortcuts for pinned toots

- src/routes/_components/IconButton.html
- src/routes/_components/shortcut/ScrollListShortcuts.html
- src/routes/_components/status/Media.html
- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusAuthorName.html
- src/routes/_components/status/StatusContent.html
- src/routes/_components/status/StatusHeader.html
- src/routes/_components/status/StatusMediaAttachments.html
- src/routes/_components/status/StatusMentions.html
- src/routes/_components/status/StatusRelativeDate.html
- src/routes/_components/status/StatusSidebar.html
- src/routes/_components/status/StatusSpoiler.html
- src/routes/_components/status/StatusToolbar.html
- src/routes/_components/timeline/Timeline.html
- src/routes/_store/computations/timelineComputations.js
- src/routes/_utils/delegate.js
- tests/utils.js
> refactor: use ids instead of attrs for delegate/shortcut/focus

- src/routes/_actions/pinnedStatuses.js
- src/routes/_database/timelines/fetchStatus.js
- src/routes/_utils/sync.js
> fix: fix pinned toots not in IDB

- src/routes/_components/dialog/components/MediaInDialog.html
> fix: fix /undefined request for video poster

- src/routes/_components/dialog/components/MediaInDialog.html
fixes #1042 for real this time
> fix: fix /undefined request for gifv

- tests/spec/012-compose.js
trying to make this test less flakey
> test: improve emoji test

- src/routes/_components/dialog/components/AccountProfileOptionsDialog.html
> fix: fix closing of account options dialog

- src/routes/_actions/addStatusOrNotification.js
- src/routes/_actions/deleteStatuses.js
- src/routes/_actions/timeline.js
- src/routes/_components/timeline/Timeline.html
- src/routes/_store/computations/timelineComputations.js
- src/routes/_store/mixins/timelineMixins.js
- src/routes/_store/observers/instanceObservers.js
- src/routes/_store/observers/timelineObservers.js
- src/routes/_utils/arrays.js
- src/routes/_utils/getIdFromItemSummaries.js
- src/routes/_utils/sorting.js
- src/routes/_utils/timelineItemToSummary.js
As described in https://github.com/nolanlawson/pinafore/issues/369#issuecomment-467211908 this is the first step toward fixing #369
> refactor: use timeline item summaries instead of ids

- src/routes/_components/InformationalFooter.html
- src/routes/_pages/settings/about.html
> fix: add a privacy policy

- src/routes/_database/constants.js
- src/routes/_utils/statusIdSorting.js
- tests/unit/test-database.js
- tests/unit/test-id-sorting.js
> fix: fix pleroma snowflake IDs for real

- package.json
- webpack/client.config.js
- yarn.lock
using a branch that allows for modern ES6 builds as well
> chore: update to latest emoji-mart

- src/routes/_static/themes.js
- src/scss/themes/mastodon.scss
In production for a while on pina.todon.nl
> Plus theme with Mastodon standard web-app colors (called mastodon) 

- now.json
it changed due to 5012a21bcdd34395171548c0e747f7e334368940
> chore: update now.json

- webpack/client.config.js
this is more like what a typical babel config looks like, although functionally it should be the same
> chore: clean up babel config

- src/routes/_components/status/Media.html
> fix: fix media button focus outline

- src/routes/_components/dialog/components/EmojiDialog.html
> fix: fix background on dark mode emoji

- CONTRIBUTING.md
> docs: update development guide

- src/routes/_actions/showMoreAndScrollToTop.js
- src/routes/_actions/timeline.js
- src/routes/_components/NavItem.html
- src/routes/_components/ShortcutHelpInfo.html
- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- src/routes/_components/timeline/Timeline.html
- src/routes/_store/computations/timelineComputations.js
- src/routes/_utils/createStatusOrNotificationUuid.js
- src/routes/_utils/scrollToTop.js
- tests/spec/024-shortcuts-navigation.js
> feat: implement "." keyboard shortcut

- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/ModalDialog.html
- src/routes/_components/dialog/components/ShortcutHelpDialog.html
- tests/spec/030-shortcuts-modal.js
- tests/utils.js
The backspace is kind of messed up in modals that open other modals; we can simplify all this.
> fix: fix and test shortcut keys in modals

- src/routes/_actions/addStatusOrNotification.js
- src/routes/_utils/arrays.js
- tests/spec/008-status-media.js
- tests/spec/010-focus.js
- tests/spec/017-compose-reply.js
- tests/spec/022-status-aria-label.js
- tests/spec/023-mark-media-as-sensitive.js
- tests/spec/025-shortcuts-status.js
- tests/spec/029-back-button-modal.js
- tests/spec/030-shortcuts-modal.js
- tests/spec/100-favorite-unfavorite.js
Didn't realize there was a built-in array function for this.
> fix: replace indexWhere with findIndex

- src/routes/_store/store.js
> Disable custom scrollbars by default on iOS

- src/routes/_components/status/StatusCard.html
> Add hostname when description is missing

- src/routes/_components/dialog/components/AccountProfileOptionsDialog.html
- src/routes/_components/dialog/components/CopyDialog.html
- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_components/dialog/components/GenericConfirmationDialog.html
- src/routes/_components/dialog/components/ModalDialog.html
- src/routes/_components/dialog/components/PostPrivacyDialog.html
- src/routes/_components/dialog/components/StatusOptionsDialog.html
fixes #1151
introduces `shrinkWidthToFit` option for some dialogs so they don't grow so wide.
> fix: fix modal dialog width

- src/routes/_components/dialog/components/GenericConfirmationDialog.html
- src/routes/_components/dialog/components/ModalDialog.html
- tests/spec/032-mute-dialog.js
> fix: fix dialogs within dialogs not opening

- src/routes/_components/status/StatusCard.html
> Unstretch the card image

- src/routes/_components/status/Status.html
- src/routes/_pages/settings/general.html
- src/routes/_store/store.js
fixes #1155
adds a new setting - "hide link preview cards"
> feat: add option to disable open graph cards

- src/routes/_components/TabSet.html
- src/routes/_components/profile/AccountProfile.html
- src/routes/_components/profile/AccountProfileFilters.html
- src/routes/_components/profile/AccountProfilePage.html
- src/scss/themes/_base.scss
Make them more compact and the hover colors more subtle, make the background match the account profile background.
> fix: redesign tabs slightly

- src/routes/_actions/autosuggestAccountSearch.js
- src/routes/_actions/autosuggestEmojiSearch.js
- src/routes/_api/search.js
- src/routes/_database/accounts.js
- src/routes/_static/autosuggest.js
- src/routes/_store/observers/autosuggestObservers.js
fixes #1005
Does a local search and a remote search in parallel and merges the results together.
> fix: do remote search when autosuggesting accounts

- src/routes/_pages/settings/instances/add.html
Just learned about this in https://webplatform.news/issues/2019-05-06
> fix: use inputmode=url for instance input

- package.json
- src/routes/_actions/autosuggestAccountSearch.js
- src/routes/_api/search.js
- src/routes/_store/observers/autosuggestObservers.js
- src/routes/_utils/PromiseThrottler.js
- src/routes/_utils/ajax.js
We should be a good citizen and not spam the server with one XHR per keystroke
> fix: throttle XHRs from autosuggest

- src/routes/_components/dialog/components/GenericDialogList.html
fixes #1201
Made the focus ring thicker in this context and fixed the cropping on it.
> fix: improve focus style on dialog list item

- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusPoll.html
This does not do much, just basics to allows user to see the results of a poll. This is part of #1130.
> Show poll results to a status

- src/routes/_components/status/StatusPoll.html
tweaks to the poll results style and fixes a11y issues with it (addendum to #1219)
> fix: tweak poll results style and fix a11y

- src/routes/_components/settings/instance/PushNotificationSettings.html
Eventually we need to add polls here, but this is just me doing some minor cleanup
> fix: minor tweaks to PushNotificationSettings

- src/routes/_components/settings/instance/GenericInstanceSettings.html
- src/routes/_components/settings/instance/HomeTimelineFilterSettings.html
- src/routes/_components/settings/instance/NotificationFilterSettings.html
- src/routes/_components/timeline/Timeline.html
- src/routes/_pages/settings/instances/[instanceName].html
- src/routes/_static/instanceSettings.js
- src/routes/_store/mixins/instanceMixins.js
- src/routes/_store/store.js
- tests/spec/033-notification-mentions.js
- tests/spec/034-home-timeline-filters.js
- tests/spec/035-notification-timeline-filters.js
- tests/spec/123-notification-mentions.js
- tests/spec/124-home-timeline-filters.js
- tests/utils.js
Fixes #1223
Fixes #1224
It's happening
> feat: add home/notification filter settings

- src/routes/_components/settings/instance/PushNotificationSettings.html
- src/service-worker.js
fixes one of the sub-tasks in #1130.
I also went ahead and removed the reply feature, because I cannot get it to work in Android 6.0.1 and I can't find any documentation for it in W3C/WHATWG, so I'm not sure how it is supposed to work.
> feat: add poll result push notifications

- bin/svgs.js
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusHeader.html
More work on #1130. Shows the poll results when the poll finishes as a notification.
> feat: add poll notifications

- bin/svgs.js
- src/routes/_actions/polls.js
- src/routes/_api/polls.js
- src/routes/_components/status/StatusPoll.html
- src/routes/_intl/formatTimeagoDate.js
> fix: show poll results, time remaining, allow refresh

- src/routes/_actions/polls.js
- src/routes/_api/polls.js
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusPoll.html
- src/routes/_store/store.js
> feat: vote on polls

- src/routes/_components/compose/ComposeBox.html
- src/routes/_transitions/slide.js
> fix: fix reduceMotion of svelte slide transition

- src/routes/_components/compose/ComposeMedia.html
- src/routes/_components/compose/ComposeMediaItem.html
use ul/li instead of divs here
> fix: improve media upload a11y

- src/routes/_components/compose/ComposeMediaItem.html
- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
- tests/utils.js
- better text contrast
- easier to see X button
- autosizing textarea instead of single-line input
> fix: improve UI/a11y of media upload

- src/routes/_components/compose/ComposeLengthIndicator.html
- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
- src/scss/themes/cobalt.scss
- src/scss/themes/pitchblack.scss
Some of these colors were really hard to distinguish and far from accessible color contrast guidelines. This improves them a bit.
> fix: improve color contrast of dark themes

- src/routes/_components/compose/ComposeToolbar.html
these buttons are too cramped on iPhone 4
> fix: fix compose button toolbar style on small devices

- src/routes/_utils/serviceWorkerClient.js
- src/service-worker.js
fixes #1243
Tested in Chrome and Firefox, need to deploy to dev.pinafore.social before I can test on iOS, but my fingers are crossed.
> fix: fix service worker for real

- src/routes/_components/Tooltip.html
> fix: Esc key dismisses tooltip

- src/inline-script/inline-script.js
- src/routes/_actions/pushSubscription.js
- src/routes/_components/settings/instance/PushNotificationSettings.html
- src/routes/_store/computations/instanceComputations.js
- src/routes/_store/mixins/instanceMixins.js
- src/routes/_store/store.js
- src/routes/_store/storeLite.js
fixes #1274
We don't have any push subscription tests, so I'll have to test manually. I also made an effort to make the old settings carry over if you're only logged in to one instance.
> fix: push subscriptions per instance

- src/routes/_components/dialog/components/ReportDialog.html
> Fix report dialog not taking comments

- README.md
This should clarify questions in #1287
> docs: update docs on exporting

- bin/svgs.js
- package.json
- src/routes/_actions/compose.js
- src/routes/_api/media.js
- src/routes/_components/Draggable.html
- src/routes/_components/LazyImage.html
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeMediaItem.html
- src/routes/_components/dialog/asyncDialogs.js
- src/routes/_components/dialog/components/MediaFocalPointDialog.html
- src/routes/_components/dialog/components/MediaInDialog.html
- src/routes/_components/dialog/creators/mediaFocalPointDialog.js
- src/routes/_thirdparty/intrinsic-scale/LICENSE
- src/routes/_thirdparty/intrinsic-scale/intrinsicScale.js
- src/routes/_utils/asyncPolyfills.js
- src/routes/_utils/coordsToPercent.js
- src/routes/_utils/events.js
- src/routes/_utils/loadPolyfills.js
- src/routes/_utils/throttleRaf.js
- src/scss/themes/_base.scss
- tests/spec/013-compose-media.js
- tests/spec/109-compose-media.js
- tests/spec/121-delete-and-redraft.js
- tests/spec/130-focal-point.js
- tests/utils.js
- yarn.lock
> feat: add ability to set focal points for media

- src/routes/_components/status/StatusPoll.html
> fix: fix poll color inside of notifications

- tests/spec/121-delete-and-redraft.js
- tests/spec/126-polls.js
- tests/spec/130-focal-point.js
I'm going to take [Martin Fowler's advice](http://martinfowler.com/articles/nonDeterminism.html) and ignore flaky tests for now. We can fix this later.
> test: skip flaky tests for now

- src/routes/_components/timeline/Timeline.html
- src/routes/_utils/events.js
> fix: use focusin/focusout instead of custom events

- src/routes/_utils/delegate.js
> fix: fix return focus on keyboard-clicking media

- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/MediaFocalPointDialog.html
- src/routes/_components/dialog/components/ModalDialog.html
> fix: clicking outside image closes modal

- src/routes/_components/status/Media.html
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusMediaAttachments.html
- src/routes/_components/status/StatusPoll.html
- src/routes/_components/status/StatusSpoiler.html
- src/routes/_components/status/StatusToolbar.html
- src/routes/_utils/delegate.js
> fix: fix event propagation for click delegates

- .travis.yml
- bin/setup-mastodon-in-travis.sh
this should actually fix the broken ffmpeg...
> chore: fix ffmpeg install in travis

- CONTRIBUTING.md
- bin/run-mastodon.js
This is failing in Travis, details in #1314
> chore: fix mastodon fuubar dependency in travis

- src/routes/_components/dialog/components/GenericDialogList.html
- src/routes/_components/status/Media.html
- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- src/routes/_utils/events.js
- src/scss/global.scss
fixes #1322
This is a weird fix, but I don't really know enough CSS to figure out why this isn't working properly, and I why I need to fix the focus outline on some elements.
> fix: use pure CSS for focus effect

- src/routes/_actions/addInstance.js
- src/routes/_pages/settings/instances/add.html
- src/routes/_static/blocks.js
I reserve the right to refuse service to anyone for any reason
> fix: add instance blocks

- src/scss/global.scss
I think it looks better if it looks like the dots are growing or
shrinking rather than the whole thing spinning.
> fix: tweak spinner animation

- src/routes/_components/compose/ComposeInput.html
- src/routes/_components/dialog/components/ComposeDialog.html
> fix: fix autosizing of delete/redraft

- src/routes/_actions/delete.js
- src/routes/_actions/deleteAndRedraft.js
Fix #1339 
(Couldn't do tests because I don't have a working mastodon dev environment)
> Use unformatted status content in deleteAndRedraft

- src/routes/_components/dialog/components/ReportDialog.html
Just some minor tweaks to the style to make this more readable
> fix: improve style of report dialog

- src/routes/_components/status/StatusContent.html
- src/scss/global.scss
> Fix the style of blockquotes, ul and li in toots

- src/routes/_utils/decodeImage.js
> fix: fix Firefox img.decode bug

- yarn.lock
Forgot to update yarn in https://github.com/nolanlawson/pinafore/pull/1371
> chore: update yarn

- src/routes/_components/dialog/components/MediaFocalPointDialog.html
Especially on mobile devices, I feel this button is a bit too small.
> fix: make focal point button a bit larger

- src/routes/_components/status/StatusContent.html
- src/routes/_utils/urlIsCrossOrigin.js
> fix: fix malformed URLs in statuses

- src/routes/_components/status/StatusMediaAttachments.html
- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
Minor tweaks to the text color as described in https://github.com/nolanlawson/pinafore/pull/1381#issuecomment-522258204
> fix: tweak colors for blurhash sensitive media button/text

- src/routes/_actions/createMakeProps.js
Don't show marks/measures unless there are actually blurhashes to decode
> fix: reduce number of blurhash performance measures

- src/routes/_pages/settings/general.html
I think the new text is easier to understand.
> fix: rename "hide all media by default"

- src/routes/_components/status/Media.html
Fixes https://github.com/nolanlawson/pinafore/issues/1399.
> fix(components/media): Autoplay and blurhash

- src/routes/_components/status/Media.html
Dislike using extra markup to solve style issues but this is the simplest fix.
Fixes https://github.com/nolanlawson/pinafore/issues/1404.
> fix(components/media): Handling of grouped videos

- src/routes/_actions/createMakeProps.js
> fix: fix blurhash for reblogged images

- tests/unit/test-measure-text.js
I may want to try to improve the performance on this, so I need tests to make sure we don't regress
> test: add test for measureText

- src/routes/_components/status/Media.html
- src/routes/_components/status/StatusMediaAttachments.html
I tried to align it with the style without blurhash (rounded corders, alignment).
I also moved the button on the left (it seemed a bit weird with two different spacing).
Closes #1397
> Fix the blurhash alignment and general style

- src/routes/_components/status/MediaAttachments.html
- src/routes/_components/status/StatusMediaAttachments.html
https://github.com/nolanlawson/pinafore/pull/1418/files#r316500431
> fix: remove unused nCols computation

- src/routes/_components/Draggable.html
The cursor for clickable areas should be the "pointer" cursor, the cursor for
draggable areas should be the "grab" cursor, and when dragging it should be the
"grabbing" cursor.
> fix: fix cursor when grabbing in draggable UI

- src/routes/_components/dialog/components/MediaFocalPointEditor.html
> fix: tweak backdrop filter in focal point editor

- src/routes/_components/dialog/components/MediaFocalPointEditor.html
Remove word "coordinate", tweak CSS a bit
> fix: tweak style of focal point coordinate inputs

- src/routes/_actions/instances.js
Only handles `401` thrown by `/api/v1/accounts/verify_credentials` - ideally all endpoints should be covered. There are some concerns with doing that:
- What if the user typed something in the compose box and we log them out when they submit the form?
- Should we add `.catch` to all requests or only once in a global place (e.g. `ajax.js`)? If we do it at a lower level we don't have access to the instance name.
- Since we launch multiple requests in parallel, the same toast might get displayed multiple times - ideally it should only happen once.
Closes https://github.com/nolanlawson/pinafore/issues/1347.
> fix(actions/instances): Clear data when token revoked

- src/routes/_utils/runTesseract.js
- src/routes/_utils/tesseractWorker.js
> perf: terminate tesseract worker after a delay

- src/routes/_actions/emoji.js
- src/routes/_components/compose/ComposeToolbar.html
- src/routes/_store/observers/instanceObservers.js
fixes #812
follow-up to #1448 and #1450
> perf: don't fetch custom emoji on every page load

- package.json
> fix: move worker-loader to dependencies

- src/routes/_database/cleanup.js
- src/routes/_static/database.js
- src/routes/_store/mixins/instanceMixins.js
- src/routes/_store/observers/cleanup.js
- src/routes/_store/observers/loggedInObservers.js
- tests/unit/test-database.js
> perf: periodically clean up old compose drafts

- src/routes/_components/status/StatusContent.html
> fix: fix case sensitivity in hashtag links

- src/routes/_components/dialog/components/MediaDialog.html
> fix: media modal uses full height on mobile

- src/routes/_components/dialog/components/MediaEditDialog.html
> fix: fix focal point on animated GIFs

- src/routes/_components/compose/ComposeBox.html
> fix: ignore rapid Ctrl-Enter inputs when composing

- src/routes/_components/search/Search.html
- src/routes/_components/status/StatusPoll.html
- tests/utils.js
fixes #3
I couldn't really find any instances where toots look "squished" on an iPhone 4, so I'm not sure what I was talking about. Polls had some style issues though, so those are fixed now. I also went ahead and improved accessibility by making the poll details an actual list with ul/li elements.
> fix: fix style/a11y of search/toots on small devices

- src/routes/_components/compose/ComposeInput.html
> fix: fix cursor position jumping on autocomplete

- src/routes/_components/NavItem.html
a11y fix, this style is a bit hard to see on nav items
> fix: improve focus style on nav item

- src/routes/_actions/deleteAndRedraft.js
- tests/serverActions.js
- tests/spec/121-delete-and-redraft.js
- tests/utils.js
> fix: delete-and-redraft preserves sensitive status

- src/routes/_actions/media.js
- tests/spec/013-compose-media.js
> fix: removing media should reset sensitive status

- src/routes/_components/Nav.html
- src/routes/_components/compose/LazyComposeBox.html
- src/routes/_components/timeline/LazyTimeline.html
- src/routes/_components/timeline/Timeline.html
Realized I'm not a big fan of `#await`; I find it much cleaner to just use `#if`.
> fix: remove svelte #await

- src/routes/_actions/addInstance.js
all we need to do is check whether we're on the client or server
> fix: simplify redirect url logic

- src/routes/_components/ShortcutHelpInfo.html
> fix: fix shortcut help dialog not keyboard-scrollable

- src/routes/_components/FreeTextLayout.html
- src/routes/_components/NotLoggedInHome.html
- src/routes/_components/community/PageListItem.html
- src/routes/_components/compose/ComposeAuthor.html
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeToolbar.html
- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_components/settings/SettingsListButton.html
- src/routes/_components/settings/SettingsListRow.html
- src/routes/_components/status/StatusHeader.html
- src/routes/_components/status/StatusSidebar.html
- src/routes/_components/status/StatusToolbar.html
- src/routes/_pages/settings/general.html
- src/routes/_pages/settings/hotkeys.html
- src/routes/_pages/settings/wellness.html
- src/routes/_store/observers/resizeObservers.js
- src/scss/focus.scss
- src/scss/global.scss
- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
- src/scss/variables.scss
Includes CSS improvements and design fixes for very small screens, e.g. the Nokia 8110 running KaiOS.
> fix: improve style on very small mobile screens

- src/routes/_components/IconButton.html
- src/routes/_components/compose/ComposeAuthor.html
- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_components/dialog/components/GenericDialogList.html
- src/routes/_components/dialog/components/ModalDialog.html
- src/routes/_components/settings/instance/ThemeSettings.html
- src/routes/_components/status/Media.html
- src/routes/_components/status/StatusPoll.html
- src/scss/focus.scss
Still trying to get Pinafore to look good on a tiny 240 pixel width KaiOS device...
> fix: more fixes for tiny screen sizes

- src/routes/_components/status/StatusContent.html
> fix: fix pleroma hashtag links

- src/routes/_store/observers/navObservers.js
Currently the nav animations are incorrect for the notifications/mentions page, this fixes that.
> fix: fix nav animation for notifications/mentions

- src/routes/_components/NavItem.html
> fix: reduce motion disables nav indicator animation

- src/routes/_store/observers/leftRightFocusObservers.js
> fix: ignore modifiers in left/right focus keys

- src/routes/_components/status/StatusPoll.html
The poll form needed a bit more padding.
> fix: improve styles on poll form

- src/routes/_components/dialog/components/GenericDialogList.html
- src/routes/_components/profile/AccountProfile.html
- src/routes/_components/profile/AccountProfileDetails.html
- src/routes/_components/profile/AccountProfileFollow.html
- src/routes/_components/profile/AccountProfileHeader.html
- src/routes/_components/status/StatusContent.html
This makes things actually show up well on the Nokia 8110 4G (KaiOS). Also went ahead and fixed some styles for iPhone 4 and other smartphones too.
> fix: more CSS tweaks for very small screens

- src/routes/_utils/shortcuts.js
- tests/unit/test-shortcuts.js
> fix: hotkeys work with caps lock on

- src/routes/_components/status/Media.html
- src/routes/_components/status/StatusMediaAttachments.html
- tests/spec/010-focus.js
> fix: return focus to sensitive media button

- src/routes/_actions/instances.js
- src/routes/_actions/timeline.js
- src/routes/_components/virtualList/VirtualListContainer.html
- src/routes/_components/virtualList/virtualListStore.js
- src/routes/_database/timelines/insertion.js
- src/routes/_store/mixins/autosuggestMixins.js
- src/routes/_store/mixins/timelineMixins.js
- src/routes/_thirdparty/quick-lru/quick-lru.js
- src/routes/_utils/asyncModules.js
> fix: fix basic login - clear store on log out

- package.json
- src/inline-script/inline-script.js
- src/routes/_static/media.js
- src/routes/_store/storeLite.js
- src/routes/_utils/runMediumPriorityTask.js
- src/routes/_utils/testStorage.js
- src/routes/_utils/userAgent.js
fixes #1546
This should fix it anyway, but I don't have an iOS 13 device, nor do I have a great setup for debugging iOS (Ubuntu sadface) so I'm mostly just guessing here.
> fix: fix uploading photos on iOS 13

- src/routes/_actions/addInstance.js
- src/routes/_pages/settings/instances/add.html
- tests/spec/002-login-spec.js
As described in #1552 I do not have a lot of faith in this feature, so maybe it should just be removed for now until a later release.
> fix: remove basic login mode for now

- src/service-worker.js
Fixes #1547 (hopefully).
So what was going on? The service worker intecepts fetch requests - but for some reason Safari transforms the status returned by the server from 206 to 200.
But Safari does not like a 200 for range request. So it decides there is an issue with the video.
To fix it we just follow this [stackoverflow response](https://stackoverflow.com/questions/54138601/cant-access-arraybuffer-on-rangerequest/54207122).
Unfortunately, for some reason I cannot seem to be able to test service worker with the current build setup (there is an error during the SW initialisation that does not seem related to my changes).
> Return a synthetic response for range requests in service workers

- webpack/server.config.js
I can't see any good reason to minify server code.
> fix: disable minification on server build

- src/routes/_actions/autosuggestAccountSearch.js
- src/routes/_actions/autosuggestHashtagSearch.js
- src/routes/_api/search.js
- src/routes/_store/observers/autosuggestObservers.js
- src/routes/_utils/RequestThrottler.js
- src/routes/_utils/lodash-lite.js
tweak the hashtag sort algorithm
fix issue where wrong results shown when offline or on slow network
refactor RequestThrottler
> fix: tweak autocomplete behavior

- src/routes/_components/dialog/components/GenericDialogList.html
> fix: fix wasted space in options dialog

- src/routes/_actions/compose.js
> fix: fix duplicate accounts in replies in Pleroma

- package.json
- src/routes/_store/observers/leftRightFocusObservers.js
- src/routes/_utils/asyncModules.js
- yarn.lock
For left/right arrow key navigation, switch to a small library I made to
handle this. Also make it load asynchronously, because why not.
> fix: switch to arrow-key-navigation library

- src/routes/_components/status/StatusPoll.html
- tests/spec/127-compose-polls.js
> fix: fix custom emoji in polls

- bin/build-svg.js
fixes #1616
follow-up to #1620, hopefully this is the final fix!
> fix: fix circle in svg

- .testcaferc.json
- CONTRIBUTING.md
- package.json
- tests/spec/100-favorite-unfavorite.js
- yarn.lock
testcafe has a config file now, let's use it
> test: improve testcafe test flakiness, use config file

- .travis.yml
> chore: fix travis postgres

- src/routes/_components/community/PageListItem.html
- src/routes/_components/radio/RadioGroup.html
- src/routes/_components/radio/RadioGroupButton.html
- src/routes/_pages/community/index.html
- tests/spec/037-pin-timelines.js
> fix: use radio buttons for pinning timelines

- src/routes/_components/dialog/components/MediaDialog.html
More work on #1633, improves accessibility of the media nav buttons by cleaning up the list and labels a bit.
> fix: media nav buttons should be a list

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_components/profile/AccountProfile.html
- tests/spec/038-memory-leaks.js
- tests/spyDomListeners.js
Figured out a way to check for memory leaks in DOM listeners in a test, so I figured we might as well test it. Happily, we don't seem to be leaking! I even verified that the test _would_ have caught a DOM event listener memory leak if there were one.
> test: test for DOM listener memory leaks

- src/routes/_components/FocusRestoration.html
- src/routes/_components/list/listStore.js
- src/routes/_components/timeline/Timeline.html
- src/routes/_static/pages.js
- tests/spec/010-focus.js
After reviewing our focus management code, I'm not sure how good it is, but at least now it's extractible from the Timeline (and can be used for e.g. #1658).
> refactor: refactor focus management

- src/service-worker.js
> fix(service-worker): Make API call to the right domain

- src/routes/_components/settings/SettingsLayout.html
- src/routes/_components/settings/SettingsListButton.html
- src/routes/_components/settings/SettingsNavItem.html
- src/routes/_pages/settings/instances/index.html
- tests/spec/010-focus.js
- tests/utils.js
> fix: settings pages preserve focus

- src/routes/_actions/timeline.js
- src/routes/_components/list/List.html
- tests/spec/122-replies-in-thread.js
- tests/utils.js
> fix: fix duplicates in threads

- .travis.yml
- bin/deploy.sh
This reverts commit 767fbccaff945c3f91b2e2804f0d40a2f09507d0 and
fixes #1732.
> fix: fix automatic zeit deployment

- src/routes/_components/LoadingMask.html
- src/routes/_components/toast/Toast.html
- src/routes/_components/virtualList/VirtualListHeader.html
- src/routes/_components/virtualList/VirtualListItem.html
1. we should be consistent
2. I just like slightly faster fade-in times
> fix: change all opacity animation timings to 0.2s

- README.md
- src/routes/_components/virtualList/VirtualListItem.html
> chore: update travis badge

- .travis.yml
- README.md
- package.json
Greenkeeper is being replaceed by Snyk, also in practice I've been updating deps manually anyway
> chore: remove greenkeeper

- bin/run-mastodon.js
It's useless, we can't read this debug file anyway
> test: do not write to mastodon.log in travis

- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusPoll.html
- tests/serverActions.js
- tests/spec/126-polls.js
> fix: fix polls with content warnings

- tests/spec/132-threads-and-updates.js
Add some tests that will make it easier to implement #1769
> test: add tests for thread order

- tests/spec/132-threads-and-updates.js
> test: add more tests for thread order

- tests/spec/132-threads-and-updates.js
> test: add another threading test

- src/build/template.html
> fix: use attr rather than class for focus-visible polyfill

- docs/Admin-Guide.md
> docs: improve docs in Admin guide

- src/build/template.html
> fix: add apple-mobile-web-app-capable

- src/scss/global.scss
fixes #1806
Tested on iOS, definitely fixes the issue.
> fix: fix stacking context in Safari/WebKit

- Dockerfile
> Updated Dockerfile. Referenced in #1826

- src/routes/_components/ShortcutHelpInfo.html
See: https://github.com/nolanlawson/pinafore/pull/1838
> fix: add "/" hotkey to help info

- src/routes/_api/lists.js
- tests/serverActions.js
- tests/spec/134-community.js
- tests/utils.js
This test would have caught the issue described here: https://github.com/nolanlawson/pinafore/pull/1836#discussion_r476870560
> test: add test for accessible radio buttons in /community

- src/routes/_components/list/listStore.js
- tests/spec/038-memory-leaks.js
- tests/utils.js
This test would have caught the leak in https://github.com/nolanlawson/pinafore/pull/1851
> test: count store listeners in memory leak test

- package.json
- yarn.lock
I should have done this a long time ago. Makes it a lot harder to commit lint errors.
> chore: add husky to automatically fix lint issues

- src/routes/_components/virtualList/VirtualList.html
- src/routes/_components/virtualList/virtualListStore.js
Just some housekeeping. I didn't really understand how Svelte worked at the time I wrote this code.
> fix(VirtualList): fix some TODOs

- src/routes/_components/ShortcutHelpInfo.html
- src/routes/_components/status/StatusMediaAttachments.html
- tests/spec/025-shortcuts-status.js
- tests/utils.js
> feat: add "i" as shortcut to open media

- src/routes/_components/dialog/components/StatusOptionsDialog.html
> fix: move "bookmark" button past "report"

- .circleci/config.yml
- bin/run-mastodon.js
Still not working right, hope this fixes it...
> chore: fix bundler caching in circleci

- CONTRIBUTING.md
- docs/Internationalization.md
Adds better docs on the current state of Internationaliation.
FYI @marcozehe.
> docs: add better docs on internationalization

- src/intl/de.js
- src/intl/emoji-picker/de.js
This adds German as another UI language for Pinafore.
> Add German locale

- package.json
- yarn.lock
> fix: increase sapper timeout from 5s to 5min

- src/routes/_components/shortcut/ScrollListShortcuts.html
> fix: fix up/down arrows in poll options

- bin/build-vercel-json.js
- vercel.json
I find these annoying https://vercel.com/support/articles/how-to-prevent-vercel-github-comments
> chore: disable vercel comment bot

- src/routes/_components/compose/ComposeInput.html
- src/routes/_utils/userAgent/isWebKit.js
> fix: fix cursor set incorrectly on WebKit browsers

- src/routes/_actions/emoji.js
- src/routes/_api/emoji.js
> fix: fix custom emoji in secure mode

- package.json
- src/routes/_components/compose/ComposeFileDrop.html
- yarn.lock
Can drag and drop multiple files to upload multiple at once now.
> feat: allow file-drop to accept multiple files

- src/routes/_actions/media.js
Minor regression in a toast error message during the intl work.
> fix: fix error message on media upload

- webpack/svelte-intl-loader.js
Pretty annoying during development to have the app server just crash
> chore: do not throw intl errors in dev mode

- src/routes/_utils/scheduleIdleTask.js
See https://web.dev/isinputpending/
The easiest way to see the impact of this is to type into the compose box on 6x CPU slowdown. This technique actually slightly delays keypresses a little less, although requestIdleCallback is already doing some heavy lifting here by limiting us to <~50ms per task.
> perf: use scheduling.isInputPending()

- webpack/client.config.js
Probably broke with Webpack v5
> fix: fix tesseract in dev mode

- package.json
This reverts commit eba2b1cd744f3aed89efc8ad9532cbd3b4726a45.
Seems 2 is the sweet spot based on time spent.
> fix: revert "test: reduce concurrency again (#2007)"

- src/routes/_store/computations/badgeComputations.js
- src/routes/_store/observers/badgeObservers.js
- src/routes/_store/observers/loggedInObservers.js
- src/routes/_utils/userAgent/isChromePre87.js
> feat: use web badge API to show notifications/follow requests

- src/routes/_components/profile/AccountProfileDetails.html
- src/routes/_components/settings/instance/WordFilterSettings.html
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusDetails.html
- src/routes/_components/status/StatusPoll.html
- src/routes/_thirdparty/timeago/timeago.js
- src/routes/_utils/formatters.js
fixes #2024
Should also be a modest perf improvement since we're not eagerly creating intl formatters, although I haven't benchmarked it
> fix: initialize all Intl formatters lazily

- webpack/client.config.js
This got introduced in #2029 and I somehow didn't notice, maybe because the CircleCI tests didn't run?
> test: fix lint

- src/intl/en-US.js
- src/routes/_components/dialog/components/ModalDialog.html
- src/routes/_components/dialog/creators/showAccountProfileOptionsDialog.js
- src/routes/_components/dialog/creators/showComposeDialog.js
- src/routes/_components/dialog/creators/showCopyDialog.js
- src/routes/_components/dialog/creators/showEmojiDialog.js
- src/routes/_components/dialog/creators/showMediaDialog.js
- src/routes/_components/dialog/creators/showMediaEditDialog.js
- src/routes/_components/dialog/creators/showMuteDialog.js
- src/routes/_components/dialog/creators/showPostPrivacyDialog.js
- src/routes/_components/dialog/creators/showReportDialog.js
- src/routes/_components/dialog/creators/showShortcutHelpDialog.js
- src/routes/_components/dialog/creators/showStatusOptionsDialog.js
- src/routes/_components/dialog/creators/showTextConfirmationDialog.js
- tests/unit/test-intl.js
- tests/utils.js
> fix: internationalize dialogs

- tests/spec/040-shortcuts-search.js
Hoping this will fix this flaky test
> test: fix flaky test

- src/routes/_components/compose/ComposePoll.html
> fix: increase poll answer max length to 50

- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
This is such a small thing, but it's so nifty: https://toot.cafe/@nolan/106775559189213108
> fix: add accent-color/color-scheme

- src/routes/_actions/stream/processMessage.js
- src/routes/_api/timelines.js
> fix: ignore falsy last_status

- src/routes/_components/status/StatusPoll.html
- tests/spec/126-polls.js
> fix: fix multiple-choice poll results

- src/routes/_components/Nav.html
> feat: center navbar for widths >991px

- src/routes/_utils/replaceEmoji.js
- src/server.js
git dot io is being deprecated
> chore: remove deprecate git.io comments

- .circleci/config.yml
- CONTRIBUTING.md
- bin/clone-mastodon.js
- bin/mastodon-config.js
Can't get it running locally right now, but this ought to work
> chore: update to mastodon v3.5.1

- src/routes/_components/status/Status.html
> fix: hide embeds in spoilered statuses

- src/routes/_components/status/StatusPoll.html
- src/routes/_intl/formatTimeagoDate.js
- src/routes/_utils/formatters.js
> fix: invalid date strings

- src/routes/_actions/addInstance.js
- src/routes/_actions/instances.js
- src/routes/_api/instance.js
- src/routes/_pages/settings/instances/add.html
> fix: fix login to limited federation instance

- package.json
> chore: attempt to fix flaky test

- src/intl/en-US.js
- src/routes/_components/DynamicHeading.html
- src/routes/_components/TimelineHomePage.html
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/timeline/Timeline.html
- src/routes/_pages/community/index.html
- src/routes/_pages/search.html
- tests/spec/042-headings.js
- tests/utils.js
> fix(a11y): fix number of headings

- src/routes/_api/timelines.js
> fix: do not show "signed up" notifications in mentions tab

- src/routes/_components/snackbar/Snackbar.html
> chore: bump z-index again

- src/build/template.html
- src/routes/_components/compose/ComposeStickyButton.html
- src/scss/variables.scss
Another fix for bottom nav, see https://github.com/nolanlawson/pinafore/issues/2221#issuecomment-1322295493
> fix: fix pencil button location with bottom nav

- tests/spec/025-shortcuts-status.js
- tests/utils.js
Same as #2229, but adds a test. Opening a new PR so it will run in Circle CI
> test: add test for shortcut when focus is inside status

- CONTRIBUTING.md
> docs: update mastodon dev guide link

- src/routes/_components/status/StatusPoll.html
- tests/spec/126-polls.js
- tests/utils.js
> fix: fix poll "ends at" time

- src/routes/_actions/createMakeProps.js
- src/routes/_actions/pinnedStatuses.js
- src/routes/_actions/rehydrateStatusOrNotification.js
- tests/spec/117-pin-unpin.js
Fixes #2294
Turns out pinned toots weren't getting their plaintext content or their blurhashes computed, hence the bugs described in #2294.
> fix: fix pinned status aria-label/blurhash

- tests/spec/116-follow-requests.js
Meant to add this to #2263 but messed up
>  test: add test for #2263 

- README.md
See https://nolanlawson.com/2023/01/09/retiring-pinafore/
> docs: mark as unmaintained
