- routes/_components/timeline/MoreHeader.html
Possible solution for issue #59. AFAICT from testing with VoiceOver, it appears that it's the role=dialog that causes confusion, not the aria-hidden. role=dialog also has the annoying habit of announcing whenever there are new toots, which on a firehose like the mastodon.social federated timeline is almost useless. It seems it's better off just being a normal button.
I'm still trying to figure out if I need to set focus after the button is clicked (it just focuses the first status afterwards), but so far this seems to be working okay, at least in VoiceOver.
> remove role=alert from "show more" button

- scss/themes/_dark.scss
Some have noticed that the very-deemphasized colors could use a little more contrast on dark themes, I just bumped up the lightness/opacity a little bit. They should still be darker than regular deemphasized colors.
> Increase in contrast for "--very-deemphasized" colors 

- .travis.yml
The Firefox tests are consistently failing, so there's no sense in running them if we know they're going to fail. Also use `travis_retry` because the Chrome tests do occasionally fail, but we can retry them.
> Use travis_retry, remove Firefox tests for now

- routes/_components/timeline/Timeline.html
- routes/_utils/asyncModules.js
Attempt to address #92. I think this bug may be caused by the fact that PseudoVirtualList is async. Which is probably overkill, because it's only ~10kB and it's likely to be loaded anyway.
> make PseudoVirtualList sync rather than async

- routes/_components/ExternalLink.html
- routes/_components/profile/AccountProfileHeader.html
- routes/_components/status/StatusDetails.html
Fixes #128. Based on guidance from [this document](https://www.w3.org/TR/WCAG20-TECHS/G201.html), it seems adding "(opens in new window)" is a reasonable solution. I'm not doing this for every single external link, but only for the ones where I've added a visual icon, since for those ones it's not obvious from the context that they're external links.
> Mark permalinks with icons accessibly

- routes/_components/Layout.html
- tests/spec/010-focus.js
On page load, the focus is set the main content area instead of on the nav bar.
This fixes (#99).
> focus container on page load

- tests/spec/010-focus.js
- tests/utils.js
Attempt to fix #116 by explicitly focusing. If this works, we may want to expand this to all focus tests, because I suspect this may explain why the Firefox tests were failing as well.
> Attempt to fix focus tests for #116

- package-lock.json
- package.json
I believe [this hack](https://github.com/nolanlawson/sapper/commit/c6da54184f734d16f61c967ae8121bf2ac824b36) is no longer needed since we're not using extract-text-plugin.
> remove style-loader hack

- routes/_components/ExternalLink.html
- routes/_components/status/StatusDetails.html
- routes/_pages/settings/instances/[instanceName].html
This was always an unnecessary hack, and will break in future versions of Svelte anyway since I can't do:
```js
let { class } = this.get()
```
Background: https://github.com/sveltejs/svelte/pull/1347
> remove "class" prop in favor of "className"

- routes/_components/pseudoVirtualList/PseudoVirtualList.html
In Svelte 2.0 this is no longer necessary because we can have arbitrary expressions in `#each` loops.
> remove unnecessary item wrapping

- scss/global.scss
This focus ring isn't necessary (it's just so keyboard scrolling works on page load), and it causes weird rendering issues in Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17343598/
> fix container focus rendering issue on Edge

- routes/_components/virtualList/VirtualListItem.html
If you click around on nav items very fast, then this can be null/undefined.
> fix null in virtual list item

- .travis.yml
We're not currently testing Firefox in Travis, so no need to install the package
> travis: remove firefox package

- routes/_components/status/StatusToolbar.html
All of these status toolbar buttons should line up together, whether it's "in own thread" mode or not.
> fix minor design issue

- .travis.yml
- bin/setup-mastodon-in-travis.sh
This should also reduce the test time because we don't need to install ruby/ffmpeg unless we're going to test against Mastodon
> add dedicated script for setting up mastodon deps

- bin/restore-mastodon-data.js
I have a strong suspicion this doesn't actually make the tests less flaky.
> remove sleep while restoring mastodon test data

- bin/setup-mastodon-in-travis.sh
On second thought, it's probably smarter long-term to nail down the Ruby version instead of trusting whatever Travis has.
> explicitly install ruby 2.5.0 in travis

- .travis.yml
This seems to break greenkeeper-lockfile-update.
> Revert "use "npm ci" in travis (#337)"

- .travis.yml
let's be clever and prefer `npm ci` but if that fails because of greenkeeper not updating the lockfile, we fall back to `npm i`.
> use `npm ci || npm i` in travis

- routes/_actions/addStatusOrNotification.js
- routes/_store/observers/notificationObservers.js
- routes/_store/observers/observers.js
- routes/_store/observers/pageVisibilityObservers.js
- routes/_utils/runMediumPriorityTask.js
Part of the way to improving #390.
Before this fix, if you recieved a notification while Pinafore was in a background tab, nothing would happen, because most browsers (Edge, Firefox, Chrome) don't run rAF in background tabs. Furthermore, Chrome doesn't run rIC. In this PR we detect if we're in a background tab and then avoid rAF/rIC in that case.
> fix notifications in a background tab

- routes/_components/DynamicPageBanner.html
This changes the arrow from this:
To this:
> Change arrow on back button

- inline-script.js
- server.js
- templates/2xx.html
fixes #45 in a better way than before
#441 caused some weirdness related to ServiceWorker, so this fix seems more straightforward
> remove link rel=manifest for iOS

- package-lock.json
- package.json
- routes/_components/profile/AccountDisplayName.html
- routes/_pages/settings/general.html
- routes/_store/store.js
- routes/_utils/emojifyText.js
- routes/_utils/strings.js
- tests/spec/118-display-name-custom-emoji.js
- tests/utils.js
fixes #449
Removes all emoji and custom emoji from user display names, unless the result would be an empty string. In that case, it does nothing.
> add option to remove emoji from user display names

- routes/_components/virtualList/VirtualListContainer.html
requestIdleCallback seems aggressively delayed in mobile Chrome versus mobile Firefox (on Android), so the experience in mobile Chrome is pretty bad right now as you scroll because you might have to wait a long time for white content to fill in.
I was trying to use rIC to make scrolling smoother (it's currently smoother in Firefox than Chrome), but perhaps this is too aggressive and doesn't make a difference anyway.
> don't use rIC while scrolling

- routes/_components/profile/AccountProfileFollow.html
Non-locked accounts can also have a "follow request" if Sidekiq is backed up.
> fix requested view for follow requests

- routes/_actions/follow.js
This code is nonsensical because the "account" object is actually a follow response and will never have a `locked` property. Also we'll never toast in this case because it's only for status options, and you can't see someone's status if their account is locked.
> fix incorrect toast notification for follow requests

- routes/_database/cleanup.js
Based on issues I'm seeing on iOS Safari, I'm guessing that my IDB caching is too aggressive and is hitting origin storage limits, which causes IDB transactions in safari to fail silently and never call any transaction callbacks (`onblocked`, `onerror`, `oncomplete`).
This is pretty bad and causes Pinafore to basically just not work unless you clear site data, which we should avoid. 2 weeks was probably unnecessary anyway; in a social network, who cares about content that's 2 weeks old?
> Store IDB data for 1 week rather than 2 weeks

- scss/themes/_dark.scss
this makes the colors way easier to see on the autosuggest background in the dark themes
> fix autosuggest for dark themes

- routes/_components/DynamicPageBanner.html
- routes/_components/community/PageListItem.html
- routes/_components/compose/ComposeBox.html
- routes/_components/profile/AccountProfile.html
- routes/_components/profile/AccountProfileDetails.html
- routes/_components/profile/AccountProfileHeader.html
- routes/_components/profile/AccountProfileMeta.html
- routes/_components/profile/AccountProfileNote.html
- routes/_components/status/Status.html
- routes/_components/timeline/PinnedStatuses.html
- routes/_components/timeline/Timeline.html
- routes/_pages/accounts/[accountId].html
- routes/_pages/statuses/[statusId]/index.html
This should fix the accessibility bug described in https://github.com/nolanlawson/pinafore/issues/503 as well as a few other things. I used VoiceOver to validate my assumptions, so I hope that these improvements genuinely improve the screenreader experience.
Changes:
1. add `role=term` and `role=definition` to fields
2. Ensure that every page has an `<h1>` that is non-empty even if the visual content is empty for aesthetic reasons
3. Wrap the page header `<h1>` and back button in a `<nav>` with a label to distinguish it from the main `<nav>`
4. Avoid screen reader announcing the left arrow in the back button
5. Add `<h1>` heading for pinned statuses
6. Add `<h2>` headings inside of the profile to mark name and following, description, fields, and stats
7. Make some of the timeline `<h1>`s …
> improve a11y of fields, status page, and more

- routes/_actions/timeline.js
- routes/_components/status/StatusDetails.html
- tests/serverActions.js
- tests/spec/119-status-counts-update.js
If you're looking at a stale "view" of a status, it's possible to see out-of-date fav/boost counts. This fixes that by updating it once the fetch request responds.
> update fav boost accounts for stale views

- routes/_actions/createMakeProps.js
- routes/_components/timeline/Timeline.html
this forces all worker IDB promises to resolve at the same time, fixing the issue caused by #517 where toots load in an unpredictable order
> fix worker ordering

- routes/_actions/timeline.js
- routes/_api/timelines.js
- routes/_database/timelines/pagination.js
- routes/_static/timelines.js
- routes/_store/observers/instanceObservers.js
- routes/_store/observers/timelineObservers.js
I feel like 10 is a more reasonable default than 20 and may lead to better perf because we're doing less work in a single render pass.
> lower timeline fetch batch size from 20 to 10

- routes/_static/timelines.js
If your screen is large and your notifications are mostly follows, then the timeline can fail to load.
TODO: fix that core problem instead
> switch timeline batch size back to 20

- scss/global.scss
When using a dark GTK theme `input` and `textarea` use the theme's colors by default. This makes sure that they inherit the page's colors.
Inheriting the page's color might not be desirable (see following screenshot). If that is the case we can just set it to white background with black text.
> Inherit colors for input and textarea

- package.json
- routes/_actions/pushSubscription.js
- routes/_api/oauth.js
- routes/_api/pushSubscription.js
- routes/_pages/settings/instances/[instanceName].html
- routes/_store/observers/instanceObservers.js
- routes/_store/observers/notificationPermissionObservers.js
- routes/_store/observers/observers.js
- routes/_store/store.js
- routes/_utils/base64.js
- templates/service-worker.js
Basic implementation, without ~actions,~ grouping or the complicated logic that Mastodon has for focusing existing clients when clicking the notification.
I'm not sure how this will work with multiple instances (especially when opening a new tab via the notification that is not from the current instance). I think that would need a way to pass the desired instance via the URL (as a query parameter?).
TestCafe now supports [HTTPS](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/connect-to-the-testcafe-server-over-https.html), so if that is set up I could write some basic tests to make sure that settings are saved in the backend.
No feature-detection is currently done. How would you prefer this to be handled - hide the settings entirely, disable them? I …
> Push notifications

- routes/_database/cleanup.js
Comments from heavy Mastodon users (like my wife) are that Pinafore just randomly stops working entirely, which I suspect is due to reaching database limits. It's kind of silly to store so much data, and it probably shouldn't even be limited based on time but rather on quantity, but for now reducing from 7 days to 5 days seems reasonable.
> reduce limit of stored data to 5 days

- .travis.yml
It seems Travis already has npm 6 installed, so this just adds 10 seconds to the build.
> chore(travis): no explicit npm install

- bin/restore-mastodon-data.js
This should speed up the tests by avoiding artificial delays. But I'm going to do 10 runs to make sure it actually doesn't introduce flakiness.
> avoid delaying when inserting every post in tests

- bin/run-mastodon.js
Don't re-run install commands if Mastodon is already installed.
> make mastodon installation faster in dev mode

- .travis.yml
- package.json
Instead of deploying to production manually, just grep the commit message and if it looks like a version number, deploy immediately to production.
> chore(travis): use travis to deploy to production

- .travis.yml
I don't know why I thought it would be a good idea to remove this. Greenkeeper is failing because of it.
> chore(travis); use npm ci || npm i

- routes/_utils/eventBus.js
It seems we can occasionally go over the limit of 100, and it's not a memory leak AFAICT.
> fix(eventBus): increase event listeners to 1000

- routes/_components/virtualList/VirtualListContainer.html
- routes/_utils/scrollContainer.js
I realized that the `offsetHeight` no longer works when scrolling the main document, so sometimes the infinite scroll would not work properly. This fixes #659.
> fix(scroll): fix offsetHeight for scrolling whole document

- package-lock.json
- package.json
- routes/_components/compose/ComposeInput.html
- routes/_components/dialog/components/ModalDialog.html
- routes/_thirdparty/a11y-dialog/LICENSE
- routes/_thirdparty/a11y-dialog/a11y-dialog.js
- routes/_thirdparty/autosize/LICENSE.md
- routes/_thirdparty/autosize/autosize.js
I decided to fork a11y dialog in order to achieve this. We need to delay calling `element.focus()` until after a double rAF; otherwise Chrome scrolls to the top if you focus a sticky-positioned element.
I also created a `_thirdparty` directory containing `a11y-dialog` and `autosize` which had been previously forked.
> fix(dialog): when dialog is hidden, don't scroll to top

- routes/_components/dialog/components/ModalDialog.html
Fixes #680 in desktop Firefox, Chrome, and Epiphany, as well as Android Firefox and Android Chrome. In iOS Safari it's still not fixed, but after looking over discussion in https://github.com/twbs/bootstrap/issues/22311 it seems not worth the effort to work around the Safari bug.
> fix(scrolling): fix body scrollable when modal is open

- package-lock.json
- package.json
- routes/_intl/formatTimeagoDate.js
- routes/_thirdparty/timeago/LICENSE
- routes/_thirdparty/timeago/timeago.js
This dependency was doing much more than we needed (including containing Chinese formatters), so I moved it to `_thirdparty` and stripped it down. As a result, it seems to be much more performant at runtime as well as smaller.
> fix(deps): remove timeago.js

- scss/themes/_scrollbars.scss
Also use correct SCSS escaping everywhere, and fix a missing semicolon. Fixes #691
> fix(scrollbars): use standard CSS for scrollbars

- routes/_a11y/getAccessibleLabelForStatus.js
- routes/_components/status/Status.html
- routes/_pages/settings/general.html
- routes/_store/store.js
- tests/spec/022-status-aria-label.js
Actually fixes #694 by providing an option to make the labels like they used to be.
For NVDA users, they should be able to go to the settings and tick these options:
- Remove emoji from user display names
- Use short article ARIA labels
And NVDA will no longer crash.
> feat(a11y): add option for short article aria labels

- routes/_pages/settings/general.html
This should make it easier to find the theme settings. It felt kind of hacky to include instructions here rather than just having the theme settings available.
> feat(settings): add theme settings to general

- routes/_components/status/Status.html
- routes/_pages/settings/general.html
- routes/_store/store.js
- routes/_utils/delegate.js
fixes #163. also fixed the issue where selecting text would cause the toot to be tapped
> feat(a11y): add option to disable tappable toots

- routes/_components/LazyImage.html
- routes/_components/NonAutoplayImg.html
- routes/_utils/decodeImage.js
If you turn on image blocking in Firefox for Android, then the timeline can get messed up because the heights are not calculated correctly for broken images. This fixes that.
> fix(firefox): fix firefox with blocked images

- package-lock.json
- package.json
- routes/_utils/eventBus.js
I don't see any reason not to switch. It's slightly smaller than the other events library and does everything we need.
> chore(package): use events-lights instead of events

- routes/_store/observers/instanceObservers.js
I'm pretty sure it was a mistake to call updateInstanceInfo twice here.
> chore: refactor instance observer code, remove double call

- routes/_components/virtualList/VirtualList.html
- routes/_components/virtualList/VirtualListContainer.html
- routes/_components/virtualList/virtualListStore.js
This reverts commit 36d90d34e50919016a6b8e3a2bb713766d26fc82.
Fixes #724
I'm not sure why, but it was apparently this "refactoring" commit that
broke it. Probably because it's not safe to observe a store within a
component; the observer isn't deactivated when the component is
destroyed.
> Revert "chore(store): clean up usage of svelte store (#713)"

- routes/_components/AutoplayVideo.html
- routes/_components/Avatar.html
- routes/_components/LazyImage.html
- routes/_components/NonAutoplayGifv.html
- routes/_components/dialog/components/ImageDialog.html
- routes/_components/status/Media.html
- routes/_components/status/MediaAttachments.html
- routes/_components/status/Status.html
- routes/_components/status/StatusMediaAttachments.html
- routes/_pages/settings/general.html
- routes/_store/store.js
I have generally tried to keep how the non grouped behaviour was working. 
There is one main (intentional) change for the non grouped mode. Now, in the feed mode, images are centered accounting for the sidebar.
The grouped mode (optional, off by default) tries to show the images in a nice grid – it might result in some images not always cropped nicely. 
Nevertheless, it takes in account the focus that is set by the uploader.
Closes #258
> Allow Media to be shown in a grid (as an option)

- templates/2xx.html
I believe prefetch is a better choice here, and Chrome is warning about it in the console anyway
> perf: use prefetch instead of preload for svgs

- bin/deploy.sh
correctly set robots.txt and use the URL of the newly-deployed server for the alias
> chore: fix travis deploy script

- src/routes/_components/status/StatusMediaAttachments.html
It is now slightly bigger than what images in a box would look like.
I tried to make it fit exactly, but because we use a ratio of the width, we have subpixel computations error and the flow is redrawns slightly sometimes.
I also handle the case where you can have more the 4 images (even if it looks like mastodon does not allows it).
Closes #771
> Change thesize of sensitive media box

- src/routes/_actions/addStatusOrNotification.js
- src/routes/_actions/delete.js
- src/routes/_actions/deleteStatuses.js
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/dialog/components/StatusOptionsDialog.html
- src/routes/_utils/statusHtmlToPlainText.js
- tests/spec/121-delete-and-redraft.js
fixes #786
This may also fix some flakiness in how streamed updates/deletes were being handled, because I realized that using `throttle()` here kind of makes no sense and can cause updates/deletes to just get dropped, which is kind of a bad bug. That's fixed now by using requestIdleCallback.
> fix: fix delete and redraft on replies

- src/routes/_components/status/StatusMediaAttachments.html
This fixes the padding and allows the warning to overflow.
> fix: fix sensitive content warning on mobile

- README.md
- bin/print-export-info.js
It just occurred to me that we can't handle nonces correctly when the site is exported. So for now let's just not support it, and add a note about the lack of CSP support in the README.
> fix: drop CSP support from the exported version

- src/routes/_database/databaseLifecycle.js
- src/routes/_store/LocalStorageStore.js
- src/routes/_utils/asyncModules.js
- src/routes/_utils/loadPolyfills.js
This would help with Rollup compat if we ever decided to switch to
Rollup
> fix: move page-lifecycle and idb-getall-shim to dynamic modules

- src/routes/_database/asyncDatabase.js
- src/routes/_database/database.js
- src/routes/_database/database.prod.js
- src/routes/_utils/asyncModules.js
- webpack/client.config.js
This saves some bytes (~14kB or so) from `main.js` and removes a dependency that's only needed if you're actually logged in. Uses ES6 proxy magic to achieve this.
> perf: move indexeddb operations to async module

- webpack/client.config.js
- webpack/service-worker.config.js
- webpack/terser.config.js
we can make the SW js smaller, and we still have sourcemaps
> perf: use terser for service worker too

- src/routes/_components/dialog/components/ImageDialog.html
- src/routes/_components/dialog/components/VideoDialog.html
- src/routes/_components/status/Media.html
Should fix #750 and any issue with any Mastodon Client API-compliant server that doesn't provide attachment metadata (as it's optional).
> Fix Pleroma compability issue

- .travis.yml
- package-lock.json
- package.json
It's probably about time to upgrade. I don't think we're going to 
explicitly break compatibility with Node v8, but we're also not
going to use it or test it.
> chore: upgrade travis/now to node v10

- bin/build-sass.js
- package-lock.json
- package.json
- src/routes/_actions/emoji.js
- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_components/dialog/creators/showEmojiDialog.js
- src/routes/_react/emoji-mart.js
- src/routes/_store/observers/resizeObservers.js
- src/routes/_utils/asyncModules.js
- src/routes/_utils/loadCSS.js
- tests/spec/012-compose.js
- tests/spec/108-compose-dialog.js
- tests/utils.js
- webpack/client.config.js
- webpack/server.config.js
- webpack/service-worker.config.js
- webpack/shared.config.js
Fixes #4 
Normally I would love to write everything from scratch so that the dependencies can be as small as possible, but in the case of an emoji picker it would be a huge amount of work, and ultimately we can defer all the costs of the emoji picker until the user actually clicks the emoji button, so it's not _that_ bad to use a large dependency.
So anyway, this PR uses `emoji-mart`, which is a React component, so we can use `remount` which mounts a React component as a custom element. (We already have a custom element polyfill.) But to cut down on the size, I'm using `inferno-compat` instead of React. I'm also using the lightest version of `emoji-mart`, which uses native emoji (instead of a spritesheet) and `messenger.json` (which is the smallest emoji data set). Still, the overall size …
> feat: add full emoji picker using emoji-mart

- package-lock.json
- package.json
I tried to remove prop-types from emoji-mart but it proved too hard. Also it breaks `now` not to have this in the deps for some reason
> chore: add prop-types to deps to unbreak now

- package-lock.json
- package.json
- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_react/createEmojiMartPickerFromData.js
This reduces the size of `emoji-mart` pretty substantially using these PRs:
- https://github.com/missive/emoji-mart/pull/260
- https://github.com/missive/emoji-mart/pull/258/
Also to fix a Linux emoji issue, I went ahead and added this as well:
- https://github.com/missive/emoji-mart/pull/256
> perf: reduce size of emoji-mart dep using fork

- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_store/observers/observers.js
- src/routes/_store/observers/touchObservers.js
I find it jarring if the emoji picker dialog automatically pops open the soft keyboard; it causes two extra layouts and can cause part of the dialog to be hidden. We can't detect the existence of a soft vs hard keyboard, but we can sniff for it by checking for the mobile size.
> fix(picker): only focus picker search on desktop

- src/routes/_utils/themeEngine.js
Somehow we were accidentally making requests to `theme-undefined.css` for the default theme when switching to an instance that had not set its preferred theme yet.
> fix: fix unnecessary request for theme-undefined.css

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_store/computations/autosuggestComputations.js
- src/routes/_store/computations/timelineComputations.js
- src/routes/_store/mixins/timelineMixins.js
- src/routes/_utils/lodash-lite.js
- webpack/client.config.js
This removes 3kB from the size of all JS chunks by removing some Lodash functions we can write ourselves in ES2015+.
> perf: use lodash-lite for some functions

- webpack/client.config.js
I don't think there's much reason to override these defaults. This actually reduces the non-logged-in homepage JS bundle size by 5kB, although increasing the size of all chunks by 150kB. Doesn't seem to make much sense though to think we can beat the Webpack defaults, probably better to just use the defaults here.
> perf: use webpack splitChunks defaults

- src/routes/_components/NavItem.html
- src/routes/_components/Title.html
- tests/spec/102-notifications.js
- tests/spec/105-deletes.js
- tests/utils.js
It just occurred to me that Youtube and Twitter both put the `(1)` notification indicator at the beginning of the tab title, and the Vivaldi browser at least uses this as a hint that it's a "badge". This PR fixes that by aligning with Youtube/Twitter:
> fix: add better browser notification badges

- src/routes/_components/settings/instance/ThemeSettings.html
Adds a label to each theme group (light vs dark) as referenced in #848:
> Add labels to theme groups

- src/routes/_a11y/getAccessibleLabelForStatus.js
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusSpoiler.html
- src/routes/_static/statuses.js
- tests/spec/112-status-links.js
Some ActivityPub software facilitates long form blog posts being pushed
out onto timelines.
Some ActivityPub software have toot lengths which are much larger than
Mastodon's default of 500.
This wraps spoiler tags around those statuses.
> Wrap LONG posts with spoilers

- src/routes/_components/ShortcutHelpInfo.html
- src/routes/_components/dialog/components/ShortcutHelpDialog.html
- src/routes/_pages/settings/hotkeys.html
- src/routes/_pages/settings/index.html
- src/routes/settings/hotkeys.html
Follow up to #870 - adds the hotkey shortcuts to the settings menu, so it's a bit more discoverable:
> feat: add hotkey help to settings

- src/routes/_utils/shortcuts.js
- tests/unit/test-shortcuts.js
Follow-up to #870 - the "?" key should open up the help menu.
> fix: fix question mark hotkey

- src/routes/_components/ShortcutHelpInfo.html
- src/routes/_components/dialog/components/ShortcutHelpDialog.html
- src/routes/_pages/settings/hotkeys.html
- src/routes/_store/store.js
- src/routes/_utils/shortcuts.js
Follow-up to #870 - add an option to disable hotkeys (hotkeys are enabled by default).
I can't think of why someone would want to disable these, but accessibility is tricky, and it's hard to predict how people are going to use a website, so I want to give them the option.
> feat: add setting to disable hotkeys

- src/routes/_components/status/StatusContent.html
(Reopening #543 since the bug still persists for Pleroma instances)
External links inside toots (when using a Pleroma instance) opens up in a new tab (using target='_blank') instead of the same tab.
> Make external links open in new tab

- src/routes/_components/status/StatusContent.html
Follow-up to #892 - instead of checking whether the `href` starts with a `/`, it's safer to construct a `URL` and check its origin.
> fix: use more consistent method for checking external links

- src/routes/_actions/mention.js
- src/routes/_components/NavShortcuts.html
- src/routes/_components/ShortcutHelpInfo.html
- src/routes/_components/dialog/components/AccountProfileOptionsDialog.html
- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- tests/spec/025-shortcuts-status.js
- tests/spec/026-shortcuts-notification.js
This largely fixes #895, although I may open some issues for lingering tweaks.
This adds <kbd>m</kbd> for mention and <kbd>p</kbd> to open a profile, which works across both notifications and statuses. I also cleaned up the shortcut info dialog a bit.
> feat: add more keyboard shortcuts

- README.md
We have keyboard shortcuts now, so it's no longer a "future goal"
> docs: remove mention of keyboard shortcuts

- src/scss/themes/_scrollbars.scss
Based on http://adrianroselli.com/2019/01/baseline-rules-for-scrollbar-usability.html it seems the WCAG-approved width would be 44px, but setting it to that size is comically huge from my perspective. css-tricks uses a width of 30px, and even that looks too large to my eye. But I like the suggestion of having it scale with the `em` so that users can zoom in and make it larger, so I'm using `calc(20px * 0.25em)`.
Note this only applies to Chrome/Safari (since Firefox doesn't let us set the scrollbar width), and users can disable custom scrollbars in the settings anyway.
> fix: increase custom scrollbar width

- src/routes/_components/dialog/components/MediaDialog.html
On iOS Safari, Math.round works better than Math.floor
> fix: fix rounding of scroll math on Safari

- .gitignore
- bin/svgs.js
- package.json
- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/PinchZoomable.html
- yarn.lock
Thanks to [pinch-zoom-element](https://github.com/GoogleChromeLabs/pinch-zoom) we can have a simple way to pinch-zoom on media. Click the magnifying glass, then either click the + or - icons to zoom in and out, or pinch-zoom. Tested on mobile Firefox/Chrome/Safari as well as Ubuntu touchpad and it works fine.
The reason pinch-zoom is a separate mode is because having it on by default messes up the scroll-snapping list; you can't scroll.
> feat: add pinch-zoom to media dialog

- src/routes/_components/dialog/components/MediaInDialog.html
This is an emerging web standard, but it would avoid an extra reflow for these images while they're being loaded. I tested it in Chromium with the "experimental web platform features" flag on, and it indeed does prevent the reflow if image loading is slow.
Pleroma does not have width/height for images, so we skip it in that case.
Details: https://www.chromestatus.com/feature/4704436815396864
> fix: use intrinsicsize for images/videos

- package.json
- yarn.lock
Now that all my PRs are in, there should be no more reason to use a fork.
> chore: update sapper to v0.25.0

- src/routes/_components/dialog/components/MediaDialog.html
I think it feels a bit nicer if the buttons update immediately, even before the scroll starts.
> fix: tweak carousel to show button change sooner

- src/routes/_actions/timeline.js
attempt to fix #943
This is a pretty brute-force way to do this, but hopefully it will work well enough for the moment, until we add filtering logic and be more intelligent about knowing what ID is a reply to what other ID.
> fix: do not add duplicates to threads

- src/routes/_components/dialog/components/MediaDialog.html
Feel kind of dumb for forgetting this, but a carousel is a list and so it should really use ul/li elements for better a11y.
> fix: carousel should use ul/li for a11y

- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/PinchZoomable.html
fixes #961
I was trying to avoid unnecessary DOM operations and re-layouts by just setting `pointer-events: none`, but this disables right-click-to-save.
I think it's simpler to just swap out `<pinch-zoom>` entirely. I measured the cost of tapping the magnifying glass at 4x slowdown in Chrome and it's around ~60ms which is reasonable.
> fix: allow right-click to save image

- src/routes/_components/dialog/components/MediaDialog.html
It feels better to use a key here so that Svelte can do less work when updating. I'm not seeing a big perf difference when testing, but it seems harmless to add.
> perf: use keyed each for media

- src/scss/themes/_dark.scss
This makes the settings text much easier to read, e.g. in the Ozark theme.
Before:
After:
> fix: fix legibility of settings text in dark themes

- src/routes/_components/settings/SettingsListButton.html
This just fixes a dev warning.
> fix: fix SettingsListItem missing className dev warning

- Dockerfile
- README.md
- package.json
- server.js
Fixes #972 as well as a few other things:
- #973 exposed `node __sapper__/build` to self-hosters, which is ugly. This adds `node server.js` which is our wrapper to handle the port, and is also a lot cleaner
- those running Pinafore in production on Windows (if they exist) are unbroken by removing the `PORT=4002` from the npm script
> fix: fix port not defaulting to 4002, add server.js

- src/routes/_components/NavItem.html
- src/routes/_components/NotLoggedInHome.html
- src/routes/_components/community/PageListItem.html
- src/routes/_components/compose/ComposeAuthor.html
- src/routes/_components/profile/AccountProfileDetails.html
- src/routes/_components/search/SearchResult.html
- src/routes/_components/settings/SettingsListButton.html
- src/routes/_components/settings/SettingsNavItem.html
- src/routes/_components/status/StatusAuthorName.html
- src/routes/_components/status/StatusDetails.html
- src/routes/_components/status/StatusHeader.html
- src/routes/_components/status/StatusMentions.html
- src/routes/_components/status/StatusRelativeDate.html
- src/routes/_components/status/StatusSidebar.html
- src/routes/_pages/settings/instances/index.html
Not sure why I didn't do this before. I guess I assumed that because we were using Service Worker already, there was little point in prefetching internal links. But it seems to make sense anyway, because there's still the fetching from the cache and the compilation and bootstrapping we can do in advance, e.g. when the user hovers over a link.
Probably needs a bit of testing to be sure, but seems like a good perf tweak.
> perf: prefetch all internal links

- package.json
- src/server.js
- src/server/sapperInlineScriptChecksums.js
attempt to address #985
This is a somewhat hacky solution to the problem. I'm trying to avoid nonces in favor of checksums so that (presumably) Zeit's CDN (Cloudflare I think?) can cache the content more reliable.
TODO: core HTML files are still being served with cache-control max-age=600, which I believe is hard-coded in Sapper somewhere
> fix: increase cache, use csp checksums over nonce

- src/server.js
another attempt to address #985
This is a bit hacky, but we can override Sapper's default max-age of 600.
> fix: set max-age to 3600 for html

- bin/svgs.js
- src/routes/_actions/share.js
- src/routes/_components/dialog/components/StatusOptionsDialog.html
fixes #990
This allows you to tap a the "..." next to a toot and share its text, CW (if available), and URL. I also went ahead and fixed it so that sharing/linking only applies to public statuses.
> feat: implement Web Share API

- src/server/sapperInlineScriptChecksums.js
It seems #988 occasionally breaks dev mode due to missing SW script. This fixes that.
I could have just added the 4 extra CSP checksums for dev mode, but it feels like a micro-optimization, and plus I'm worried this may break in prod, so better safe than sorry.
> fix: fix broken CSP in dev mode

- src/server.js
another attempt to address #985
Based on the Cloudflare docs, it seems "public" may convince it to cache it.
> fix: use "public" for cache-control

- src/service-worker.js
- webpack/client.config.js
As of #998 we can no longer rely on JS files containing "$", let alone "$polyfill$". This was a nice idea, but it's just not maintainable anymore nor does it provide a huge benefit.
> fix: remove deferred polyfill caching

- package.json
- yarn.lock
Going to temporarily go back to using a fork of Sapper because I would like to get these PRs in (especially the link rel=preload one):
- https://github.com/sveltejs/sapper/pull/566
- https://github.com/sveltejs/sapper/pull/568
> fix: use fork of sapper for now

- src/routes/_pages/blocked.html
- src/routes/_pages/muted.html
- src/routes/_pages/pinned.html
- src/routes/_pages/requests.html
- src/routes/_pages/settings/about.html
Unfortunately it looks like `sapper export` works by crawling the
non-logged-in site, which means that any pages that are inaccessible
when you're not logged in don't get generated, including "pinned,"
"muted," "blocked," "requests," and "share."
Normally this isn't a problem, but it is in browsers that don't
have Service Worker; you get a 404 when you try to refresh those pages.
My fix is to just add a hidden div that links to these pages. It's not
pretty, but it works.
> fix: add some pages that "sapper export" missed

- src/routes/_pages/community/index.html
- src/routes/_pages/settings/about.html
For reasons that are mysterious to me, #1000 works in Node v10 but not v8. And Zeit runs v8. Moving the hidden links to a different page fixes it. ¯\\\_(ツ)_/¯
> fix: fix missing export pages in node v8

- bin/build-now-json.js
- now.json
- package.json
This makes the `now.json` slightly less hacky by generating it rather than writing a bespoke regex to try to catch everything.
This also opens up the possibility of maybe injecting link rel=prefetch headers and CSP checksums into the individual headers for individual HTML files, but I can't get it working right now, because what I build locally ends up with a different Webpack checksums in the filepaths than what Zeit generates on their server.
> chore: use a script to generate the now.json

- src/routes/_components/compose/ComposeToolbar.html
- tests/utils.js
It still makes me nervous to have this in production, but at least this way the component cleans up memory when it's destroyed.
> fix: remove __fakeFileInput, clean up on destroy

- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- src/scss/global.scss
- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
I don't like clicking on a status, clicking back, and suddenly it has a
different background. The focus ring is less distracting. Unfortunately
it doesn't look right on the article element itself, so we have to apply
the style to its parent, but that's not too hard.
> fix: use focus ring rather than background for status/notifications

- src/routes/_components/compose/ComposeInput.html
- src/routes/_components/status/StatusToolbar.html
- src/routes/_components/timeline/Timeline.html
This should fix #840. I can't see any reason why we would want it to scroll when we're focusing these things.
> fix: fix timeline jumping on focus

- package.json
Right now if you run `yarn build` while port 4002 is in use, it will
fail. Let's just pick a random port that's unlikely to be used by any
self-hosters. I chose a random 5-digit number.
> fix: when building, use a port unlikely to be in use

- .nowignore
I want dev.pinafore.social to be ignored by search engines
> chore: don't let now ignore robots.txt

- CONTRIBUTING.md
- Dockerfile
- README.md
node_modules size when not running `--production`: 296M
node_modules size with `--production`: 111M
Related: #1064
> perf: reduce install size using yarn --production

- src/routes/_components/ShortcutHelpInfo.html
This reduces the size of KeyboardShortcutHelpInfo.html from 16.96kB to 2.92kB. Kind of a dumb hack, but it just doesn't feel like a bunch of static HTML should cost this much.
> perf: reduce size of ShortcutHelpInfo.html

- Dockerfile
Cleaning cache allows reduce image size from 388M to 189M
> Clean yarn cache during docker image build phase

- package.json
- src/routes/_database/cache.js
- src/routes/_database/cleanup.js
- src/routes/_database/constants.js
- src/routes/_database/databaseLifecycle.js
- src/routes/_database/helpers.js
- tests/indexedDBShims.js
- tests/unit/test-database.js
- yarn.lock
Adds unit tests using fake-indexeddb.
#1074 was making me a bit nervous because I realized we didn't really have any tests for the database itself. In this PR I do some basic smoke tests for the database, as well as ensure that the migration from v10 to v11 works okay.
Interestingly this actually did uncover a bug in how the cache should be emptied after a database is deleted, so it has a nice fix in there as well.
> test: add IndexedDB tests

- src/routes/_utils/statusIdSorting.js
- tests/unit/test-id-sorting.js
Pleroma uses numbers, upper case, and then lower case for its ordering for base62.
> Fix reversed base62 encoding

- src/routes/_database/databaseLifecycle.js
this allows the error to actually be logged in production for better debugging
> fix: when idb is blocked, use console.error

- webpack/client.config.js
I was not ever really looking at this, and it seems to add compilation time
> perf: remove stats.json from webpack

- src/routes/_components/TimelineHomePage.html
- src/routes/_components/compose/ComposeAuthor.html
- src/routes/_components/compose/ComposeBox.html
fixes #1076
Even if IndexedDB is busted or something, and for that reason $currentVerifyCredentials isn't available, the user should still be able to at least try to toot. Also it's less jarring if everything is laid out more-or-less normally on the page while we wait on IndexedDB.
> fix: always show the home compose box

- src/routes/_utils/statusHtmlToPlainText.js
Pleroma does not wrap content in `<p>` tags.
> fix: fix aria-labels for pleroma

- src/build/template.html
`initial-scale=1` was a workaround for a orientation change bug, that was only needed for the no longer relevant Safari for iOS < 9.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ref:
* https://www.quirksmode.org/blog/archives/2013/10/more_about_scal.html
* https://twitter.com/ppk/status/829329567219343360
> fix: remove no longer needed `initial-scale=1`

- src/inline-script/inline-script.js
With the release of iOS 12.2, the OAuth PWA workflow can work. I tested it on my iPhone and iPad.
Closes #1058
> Enable PWA support for iOS devices

- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusCard.html
Closes #740. The card info is returned from the Mastodon interface, so it is easier than what was argued there.
> Add support for Open Graph cards

- src/routes/_components/status/StatusCard.html
Slight visual tweaks to #1121:
- font-weight: 500 doesn't show up very well on Firefox, but 600 does
- some embeds don't have descriptions (e.g. YouTube); in those cases Mastodon uses the provider name
> fix: slight tweaks to opengraph card

- bin/svgs.js
- src/routes/_components/status/StatusCard.html
I don't like that opengraph cards without images don't show any description. So this adds a little placeholder icon like what Mastodon uses.
> fix: add placeholder icon for opengraph cards without images

- bin/svgs.js
- src/routes/_components/status/StatusCard.html
It feels like a waste of space, especially when shown on mobile devices (as in the picture).
> Remove placeholder for cards without images

- src/routes/_components/settings/SettingsListButton.html
- src/routes/_pages/settings/index.html
The iOS PWA version does not allow you to reload the page - even with killing the app. 
With this feature the user can reload for new versions of the app. It makes it possible to solve bad transient state issues as well.
> Add a setting to reload the page

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeFileDrop.html
- src/routes/_components/dialog/components/ComposeDialog.html
- src/routes/_components/dialog/components/CopyDialog.html
- src/routes/_components/dialog/components/GenericDialogList.html
- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/ModalDialog.html
- src/routes/_components/dialog/components/ReportDialog.html
- src/routes/_components/status/MediaAttachments.html
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusCard.html
- src/routes/_components/status/StatusComposeBox.html
- src/routes/_components/virtualList/VirtualList.html
- src/routes/_components/virtualList/VirtualListItem.html
- src/scss/global.scss
There was a small visual bug when trying to have a small column in an environment with scrollbars (for instance small desktop PWA).
Before:
After:
> Manage the width to take scrollbars into account

- src/routes/_components/compose/ComposeAuthor.html
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/dialog/components/ComposeDialog.html
- tests/spec/029-back-button-modal.js
- tests/spec/118-display-name-custom-emoji.js
- tests/utils.js
fixes #1159
I also went ahead and made the profile image aria-hidden, because it's redundant since there's already a link to the profile from the user name.
> fix: don't allow profile clicks from compose dialog

- package.json
It is unlikely that we will update to Svelte v3 anytime soon, if ever. Our versions of Svelte/Sapper are probably frozen in time.
> chore: make greenkeeper ignore svelte for now

- src/routes/_components/dialog/components/EmojiDialog.html
The autofocus is unreliable sometimes, adding a `setTimeout` fixes it
> fix: fix autofocus in emoji dialog search

- src/routes/_components/Tooltip.html
- src/routes/_pages/settings/instances/add.html
- src/scss/themes/_base.scss
In case folks don't know what an instance is, they can click or hover the text and get a tooltip explaining it. I implemented my own accessible tooltip for this.
> fix: add tooltip info on what an instance is

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_components/compose/ComposeAutosuggestionList.html
- src/routes/_components/compose/ComposeInput.html
- src/routes/_store/computations/autosuggestComputations.js
- src/routes/_utils/createAutosuggestAccessibleLabel.js
- tests/utils.js
fixes #129
This makes the autosuggestion list accessible. I used the approach recommended by @MarcoZehe in [this example](https://haltersweb.github.io/Accessibility/autocomplete.html).
The target implementation is a pretty standard (AFAICT) use of `aria-activedescendent` and `role=listbox`, with the major difference being that there is a sneaky `aria-live="assertive"` which is used to speak the selected option whenever it changes. I found that this was necessary to get VoiceOver to actually announce anything as you press up and down.
The use of `aria-describedby` on the `textarea` is also a nice place to put the basic usage instructions for the autosuggest (i.e. press up or down, press enter).
The only way I deviated from the target implementation is that, as you are typing, the first …
> fix: make autosuggestion accessible

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeToolbar.html
fixes #1185
This is still not perfect (the `100vw` doesn't take the scrollbar into account, and inside a dialog it doesn't properly display "over" the dialog), but it's better than before.
> fix: fix autosuggest width on mobile

- src/routes/_actions/autosuggestAccountSearch.js
new order is local first, followed by remote, and each sorted alphabetically
> fix: fix autosuggested accounts order

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_components/compose/ComposeInput.html
- src/routes/_store/mixins/autosuggestMixins.js
- src/routes/_store/observers/autosuggestObservers.js
This fixes a sudden flash of searched content when you press Enter or click a selection in the autosuggest.
> fix: fix flash of searched content in autosuggest

- bin/browser-shim.js
- package.json
- src/routes/_api/TimelineStream.js
- src/routes/_store/LocalStorageStore.js
- src/routes/_utils/asyncModules.js
- webpack/server.config.js
attempt to address #14
I can't prove for certain that this will fix the issue, but according to Google's [Page Lifecycle docs](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#developer-recommendations-for-each-state) this is the recommended approach.
I also got rid of the dynamic imports because they weren't saving us much.
> fix: close/open websocket on freeze/resume events

- package.json
- src/routes/_database/databaseLifecycle.js
- src/routes/_database/knownInstances.js
- src/routes/_thirdparty/idb-keyval/LICENCE
- src/routes/_thirdparty/idb-keyval/idb-keyval.js
Another attempt (on top of #1195) to address #14. Closing IDB connections is apparently another one of those [page lifecycle best practices](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#developer-recommendations-for-each-state); maybe this will improve our freeze/resume behavior, or at least lower our resource usage.
I opened a PR on the original idb-keyval library (https://github.com/jakearchibald/idb-keyval/pull/65), but to avoid blocking myself and to start testing on dev.pinafore.social I forked the library.
> fix: close IDB connections when page is frozen

- src/routes/_components/dialog/components/CopyDialog.html
- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/ModalDialog.html
- src/routes/_components/dialog/components/ReportDialog.html
fixes #1202
It turns out there are a few places where we broke subtle modal dialog behavior due to #826. The fix is to wait for an event where the modal says it's open, rather than using the oncreate event.
> fix: fix some dialog state issues

- src/routes/_api/TimelineStream.js
I dunno if this will improve #14, but it at least aligns us with Mastodon's behavior.
> fix: use fibonacci instead of exponential when streaming

- src/routes/_store/computations/autosuggestComputations.js
It's annoying when you type something like `@foo.` and it keeps autosuggesting even though you've typed a dot. Mastodon actually allows dots in usernames (https://github.com/tootsuite/mastodon/pull/6844) but I'm going to ignore that for the purposes of autocomplete because it's rare and will cause more problems than it solves to allow it in autosuggest.
> fix: don't autosuggest when text ends with punctuation

- src/inline-script/inline-script.js
- src/routes/_utils/themeEngine.js
Some self-hosters change the default theme, but this doesn't change which theme is embedded in the HTML as opposed to loaded via external CSS. So it's more correct to separate out these two things, and less likely to break self-hosters who change this behavior.
> fix: separate "inline theme" from "default theme"

- src/routes/_pages/settings/general.html
fixes #1215
I settled on "Show sensitive media by default" and "Hide all media by default"
> fix: change wording in show/hide sensitive media

- src/routes/_components/status/Status.html
It's not tappable, so it shouldn't have cursor:pointer.
> fix: statuses in own thread should not have cursor:pointer

- src/routes/_pages/settings/index.html
- src/routes/_utils/serviceWorkerClient.js
- src/service-worker.js
fixes #1243
Sadly it looks like Chrome changed their implementation, which is why in Chrome you currently have to reload twice. I did find a solution that works in both Chrome and Firefox (thank you smoosh.app for boilerplate Service Worker code I can copy-paste).
Although unfortunately it means that the "reload" button in the snackbar toast is now the only way to actually update the Service Worker - browser reload does not work. The worst part about that is that it's not very accessible, because keyboard users can't get to the button if they're in an infinite list. On the bright side, you can just navigate to the settings and then get to the button that way, although it's a bit janky.
I still think this solution is slightly better, though, since it probably confuses Chrome users when …
> fix: no need for double reload of SW in Chrome

- src/routes/_components/status/StatusCard.html
- src/routes/_thirdparty/unescape/LICENSE
- src/routes/_thirdparty/unescape/unescape.js
It seems a lot of servers like WordPress and GitHub encode the OpenGraph titles/descriptions as HTML. Things like `&nbsp;` and `&#39;` look really ugly. This fixes that.
> fix: unescape html in card titles/descriptions

- src/routes/_actions/timeline.js
- src/routes/_components/timeline/LoadingFooter.html
- src/routes/_components/timeline/Timeline.html
- src/routes/_pages/settings/general.html
- src/routes/_store/store.js
- tests/spec/036-disable-infinite-load.js
- tests/spec/128-disable-infinite-load.js
- tests/utils.js
fixes #391 and fixes #270. Also makes me less nervous about #1251 because now keyboard users can disable infinite load and easily access the "reload" button in the snackbar footer.
This option makes it so that new items at either the top or bottom of the timeline never load automatically. Instead, there is just a button to "show more" at both the top and bottom.
> feat: add option to disable infinite scroll

- src/routes/_pages/settings/index.html
- src/routes/_utils/serviceWorkerClient.js
- src/service-worker.js
This reverts commit fa2eb8fe52e985185a7157cca31ba57382609734.
Unfortunately it looks like we're going to have to fix #1251 in stages. The issue is that I need to account for the situation where a _new_ service worker is controlling an _old_ page. The new SW thinks it just needs to wait for a postMessage to call `skipWaiting`, whereas the old page will never do that - it will just try to refresh.
This seems bad enough that an iOS Safari app is just permanently stuck. In other browsers you have to completely close and reopen the browser in order for the page to update. That's just unacceptable.
> Revert "fix: no need for double reload of SW in Chrome (#1251)"

- src/routes/_components/compose/ComposeToolbar.html
These icons need to be closer together still
> fix: fix compose toolbar on iphone 4 again

- src/build/template.html
- src/inline-script/inline-script.js
- src/routes/_store/observers/grayscaleObservers.js
- src/scss/global.scss
Applying `filter: grayscale(100%)` to the entire `body` seems to cause weird behavior in Firefox - scrolling is kind of messed up, the header doesn't stick, the sticky button is off, and modals may be offscreen. To fix that, we can just apply grayscale to individual elements.
> fix: fix grayscale in firefox

- src/routes/_components/TimelineHomePage.html
- src/routes/_components/compose/LazyComposeBox.html
- src/routes/_utils/asyncModules.js
It just occurred to me that we are unnecessarily loading this component on the non-logged-in home page.
> perf: lazy-load the ComposeBox

- src/routes/_components/compose/ComposeMediaItem.html
- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/dialog/components/MediaInDialog.html
- src/routes/_components/status/Media.html
- src/scss/themes/_base.scss
This is a new thing in Mastodon v2.9. I kept the "camera" icon because I like it better than the paperclip, and I think it covers the 99% use case.
> feat: add support for audio attachments

- src/routes/_components/compose/ComposeMediaItem.html
Focal points are not supposed to be shown for videos, gifs, and audio apparently.
> fix: focal point should be only visible for images

- src/routes/_utils/delegate.js
I want to avoid making this mistake in the future
> fix: add warnings when click delegates return non-booleans

- src/routes/_actions/addInstance.js
Follow-up to #1326 - have to make sure that appending a port (e.g. `:80`) is not a workaround for the block.
> fix: correctly parse hostname for instance block

- src/routes/_api/search.js
40 is too much, also this aligns us with the Mastodon frontend UI.
> fix: limit search results from 40 to 5

- src/routes/_actions/deleteAndRedraft.js
- tests/spec/121-delete-and-redraft.js
- tests/spec/127-compose-polls.js
- tests/utils.js
fixes #1342
Unfortunately we can't preserve the poll expiry time, but we can preserve everything else.
> fix: delete-and-redraft preserves polls

- src/scss/custom-scrollbars.scss
I always thought that the custom scrollbars looked weird on subscrollers (e.g. in the report dialog or the compose dialog). This fixes it so they're only applied at the top level.
> fix: only apply custom scrollbars to root scroller

- src/routes/_utils/massageStatusPlainText.js
- src/routes/_utils/massageUserText.js
- src/routes/_utils/statusHtmlToPlainText.js
Along with #1348, this fixes the style of Markdown content from glitch-soc (while still not breaking Pleroma).
Before (note the extra padding):
After (note no padding):
> fix: fix html style of glitch-soc markdown content

- src/routes/_utils/themeEngine.js
This was a typo on my part; if the browser is set to prefer dark mode and the user ticks the grayscale box in the settings, then it should choose dark grayscale.
> fix: fix grayscale wellness setting in dark mode

- src/routes/_components/NavItem.html
As far as I can tell, this attribute is not used anywhere.
> fix: fix useless nav-indicator-key attribute

- src/routes/_actions/stream/streaming.js
- src/routes/_api/timelines.js
Not sure how these bugs managed to slip in (one has been there for awhile), but these are clearly errors.
If we had better tests for the streaming gap (e.g. to check that >40 statuses are filled into the gap), then we probably could have caught these.
> fix: fix bugs in streaming gap

- package.json
- src/routes/_store/observers/resizeObservers.js
- src/routes/_store/store.js
- src/routes/_utils/getMainTopMargin.js
- src/routes/_utils/themeEngine.js
There is really no reason to call window.matchMedia instead of just matchMedia.
> fix: simplify window.matchMedia

- src/routes/_actions/stream/fillStreamingGap.js
- tests/spec/107-streaming-gap.js
fixes #1356
Turns out 20 is the limit, not 40. So we fetch in batches of 20.
> fix: large streaming gaps by refetching

- src/service-worker.js
Apparently Firefox desktop requests this file every time you refresh, so putting it in the SW cache can avoid an unnecessary 304. We already do this for all the Android icons anyway.
> perf: put apple touch icon in service worker cache

- src/inline-script/inline-script.js
It occurs to me that prefetch doesn't make much sense here, because the resource may be cached, in which case the browser won't connect. What we really want is to make the timeline request start faster, but that's tricky to do with any of the existing prefetch/preload/preconnect primitives because of the Authorization header. So the best thing to do is probably just a preconnect so the browser knows to start connecting to the instance.
> perf: do preconnect instead of prefetch for instance

- src/routes/_components/status/Status.html
This is an expensive operation that is only needed for a very minor feature, so let's shortcut it.
> perf: avoid measureText() where possible

- src/routes/_components/compose/ComposeInput.html
- src/routes/_components/virtualList/VirtualListItem.html
- src/routes/_utils/RealmStore.js
- src/routes/_utils/requestPostAnimationFrame.js
Reads from the DOM should go in rPAF, writes to the DOM should go in rAF. This gets rid of the Chrome "forced layout" warnings. (At least, most of them. We still need `requestPostAnimationFrame` to actually be implemented in a browser to give us the most accurate timing.)
> perf: use requestPostAnimationFrame to reduce layout thrashing

- src/service-worker.js
If the notification couldn't be fetched fallback to displaying all notifications (aligned with how the Mastodon Web UI [handles it](https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/service_worker/web_push_notifications.js#L118)).
Might fix https://github.com/nolanlawson/pinafore/issues/1365.
> fix(service-worker): Open notifications if no status

- package.json
- src/routes/_components/LazyImage.html
- src/routes/_components/NonAutoplayGifv.html
- src/routes/_components/status/Media.html
- src/routes/_components/status/MediaAttachments.html
- src/routes/_components/status/StatusMediaAttachments.html
- src/routes/_pages/settings/general.html
- src/routes/_store/store.js
- src/routes/_utils/blurhash.js
- src/routes/_utils/decodeImage.js
- src/routes/_workers/blurhash.js
- tests/spec/008-status-media.js
- tests/spec/023-mark-media-as-sensitive.js
- tests/spec/025-shortcuts-status.js
- yarn.lock
Todo:
Closes https://github.com/nolanlawson/pinafore/issues/1179.
> feat(media): Blurhash

- src/routes/_components/status/StatusMediaAttachments.html
Slightly tweaks the top position of the "show sensitive" button when in blurhash mode. I find it looks a bit better with a bit of extra padding.
> fix: tweak position of sensitive media button in blurhash mode

- package.json
- src/routes/_actions/createMakeProps.js
- src/routes/_components/status/Media.html
- src/routes/_static/blurhash.js
- src/routes/_utils/blurhash.js
- src/routes/_workers/blurhash.js
- yarn.lock
As described in https://github.com/nolanlawson/pinafore/pull/1381#issuecomment-522258204 I would like to avoid the "pop" where the blurhash suddenly shows after the worker is done decoding it. This moves blurhash decoding into the same point in time when we asynchronously fetch status data from IndexedDB or the cache, so it happens before status rendering.
Other changes:
- Use promise-worker because I wrote it and I like it :)
- Add some perf marks/measures so I can get a better idea of the timeline
- Move `init()` of worker a bit earlier
I'm still dissatisfied with the worker round-trip time (on my local Chrome desktop it seems to take like a few hundred milliseconds... is that normal? is it just a dev tools artifact?). Also I'd like to move the cache away from the worker if we can't fix …
> fix: move blurhash worker operations to before status rendering

- src/routes/_utils/decodeImage.js
> fix: remove firefox UA sniff for img.decode

- src/routes/_workers/blurhash.js
I propose we leave the implementation in place so we can easily test later on if the performance improved.
> fix(workers/blurhash): Don't use OffscreenCanvas

- src/routes/_pages/settings/general.html
- src/routes/_pages/settings/hotkeys.html
- src/routes/_pages/settings/wellness.html
This increases the clickable area for the `input` while also making sure that there is no "dead" space between the list items. It also gets rid of having to keep the ids in sync with the `for` attribute.
(the `span` was added to the DOM to illustrate the area)
> feat(settings): Increase clickable area

- package.json
- src/routes/_database/cache.js
- src/routes/_thirdparty/quick-lru/license
- src/routes/_thirdparty/quick-lru/quick-lru.js
- src/routes/_utils/RealmStore.js
- src/routes/_utils/blurhash.js
- tests/unit/test-quick-lru.js
- yarn.lock
fixes #1402
I forked quick-lru to do this. The added benefit is that I could remove a bunch of unused code from that module.
> perf: call revokeObjectURL() on stale blurhash blob URLs

- src/routes/_utils/blurhash.js
- webpack/client.config.js
- webpack/server.config.js
This avoids ESLint complaining about the `worker-loader!` declaration
> fix: move worker-loader to webpack config

- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeInput.html
- src/routes/_thirdparty/autosize/autosize.js
1. Throttle using the technique described in [my blog post](https://nolanlawson.com/2019/08/11/high-performance-input-handling-on-the-web/))
2. Syncing to the store is debounced via requestIdleCallback
3. textarea auto-resizing happens more instantly now, which looks nicer
Profiling indicates this is about the same as before, but more consistent, probably because I'm aligning with rAF rather than throttling to an arbitrary 100ms.
> perf: improve input responsiveness in compose input

- src/routes/_components/compose/ComposeContentWarning.html
- src/routes/_components/compose/ComposeMediaItem.html
- src/routes/_components/compose/ComposePoll.html
Follow-up to #1413. Try to be more consistent about using requestIdleCallback everywhere, and to do it the same way across all the input elements in the ComposeBox.
> perf: be more consistent about compose input scheduling

- package.json
- src/routes/_components/NonAutoplayGifv.html
- src/routes/_components/status/Media.html
- src/routes/_components/status/MediaAttachments.html
- src/routes/_components/status/StatusMediaAttachments.html
- src/routes/_utils/blurhash.js
- src/routes/_utils/convertCssPropertyToDataUrl.js
fixes #1421
1. Make blurhash the logical default - if it's sensitive, then it's blurhash
2. If the blurhash is missing (e.g. Pleroma) or disabled (e.g. in the settings), then convert `--mask-bg` into a data URL and treat that as the blurhash
This slightly changes the way things look when blurhash is disabled (e.g. instead of a solid color, you'll see white gaps between multiple images), but I think that's fine.
> fix: ensure "disable blurhash" setting is honored

- src/routes/_components/status/Media.html
- src/routes/_components/status/MediaAttachments.html
It makes me nervous to have overly-generic selectors on the right-hand-side of a CSS selector. I know [browsers have optimized this](https://calendar.perfplanet.com/2011/css-selector-performance-has-changed-for-the-better/) but bloom filters can still report false positives, so it's best to err on the side of caution here, especially since it's easy to add a class name to the inline media elements.
> perf: use more efficient CSS selectors for inline media

- package.json
- src/routes/_api/stream/TimelineStream.js
- src/routes/_thirdparty/websocket/LICENSE
- src/routes/_thirdparty/websocket/backoff.js
- src/routes/_thirdparty/websocket/websocket.js
- yarn.lock
Yet another attempt to fix longstanding issues of "my notifications don't arrive after I open Pinafore after a long time" (#14).
- Fork `@gamestdio/websocket`
- Use a max fibonacci backoff of 60 seconds
- When online/offline state changes, reset the websocket connection
- When the tab becomes active (either unfrozen or reopened from a background tab), then if the websocket connection is not open, reset the fibonacci backoff and refresh the websocket connection
This is kind of risky code but I'm really trying hard to fix all these "I don't want to have to refresh to see my notifications" problems.
> fix: reset websocket on online/offline/active events

- src/routes/_actions/media.js
- src/routes/_components/dialog/components/MediaAltEditor.html
- src/routes/_utils/mediaUploadFileCache.js
- src/routes/_utils/runTesseract.js
If the user has just uploaded a media file, we still have the File object in case they want to run OCR on it. (If they refresh the page, this goes away.) Preferring local blob URLs for those Files has a few advantages:
1. Avoids unnecessary download of file the user just uploaded
2. Avoids CORS issues if the Mastodon instance doesn't support CORS
3. Avoids the bug where tesseract will fail forever if a download fails (the download of a blob URL cannot fail)
> fix: prefer local file URLs for OCR

- src/routes/_actions/media.js
- src/routes/_components/dialog/components/MediaAltEditor.html
The id may be the same across instances but the URL is not. So it's safer to use the URL as the key.
> fix: use url over id as media upload cache key

- src/routes/_store/observers/instanceObservers.js
They are already fetched on-demand when the community column is loaded.
Part of https://github.com/nolanlawson/pinafore/issues/812.
> refactor(store/observers/instance): Don't fetch lists eagerly

- src/routes/_actions/lists.js
- src/routes/_store/observers/instanceObservers.js
- src/routes/_utils/sync.js
follow-up to #1448, I would like for there not to be a flash on the /community page where the lists suddenly load in, but I would still like to avoid the network request if possible. So when the page first loads, we can load the lists from the database and only fetch them from the network if not in the cache.
also related to #812
> perf: fetch lists from database on page load

- src/routes/_components/dialog/components/MediaEditDialog.html
The dialog is in its own document, so the heading level should start
back at h1.
> fix: h2 in media edit dialog should be h1

- src/routes/_components/LengthIndicator.html
It should say "5 characters over limit", not "-5 characters over limit"
> fix: length indicator aria-label should not be negative

- src/routes/_components/dialog/components/MediaEditDialog.html
This reverts commit 450785ea81590db7b8b09e7284ed0fc3ebfe68cd.
Just realized the dialog already has an h1, so the h2 is actually correct.
> fix: Revert "fix: h2 in media edit dialog should be h1 (#1453)"

- src/routes/_database/cleanup.js
The comment is wrong; IDB does not run in a web worker currently.
> fix: run idb cleanups in requestIdleCallback

- src/routes/_store/observers/cleanup.js
- src/routes/_store/observers/nowObservers.js
- src/routes/_utils/scheduleInterval.js
There's no point in running localStorage cleanups when the page is not active. Plus I can abstract out this concept of an active-only `setInterval`.
> perf: disable database cleanups when page is not active

- src/routes/_components/compose/ComposeToolbar.html
- src/routes/_static/media.js
fixes #1461
I decided against changing the camera icon to the paperclip icon for now because I think the paperclip icon looks ugly (it's not square-ish like the other icons, so looks out of place). Also image/video is the 99.5% use case, so it's less confusing to the average user to have a camera icon. I did add a title/aria-label to indicate that audio is accepted, though.
The current Safari solution of using `accept=*/*` to allow audio is not great, but we have to wait for the WebKit bug to get fixed before changing it.
> fix: allow audio uploads on iOS Safari

- src/routes/_components/profile/AccountProfileHeader.html
- src/routes/_utils/getImageNativeDimensions.js
fixes #1464
Tested with both GIF avatars and regular avatars. Apparently MP4s aren't supported for avatar images.
> feat: clicking avatar opens media modal

- src/routes/_actions/contentWarnings.js
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeContentWarning.html
- src/routes/_components/compose/ComposeMediaItem.html
- src/routes/_components/compose/ComposeMediaSensitive.html
- tests/spec/109-compose-media.js
- tests/utils.js
fixes #1297
With this fix, media can be marked as sensitive whether or not there is a content warning. A checkbox is added to toggle sensitivity, just like the Mastodon UI.
The checkbox will automatically turn itself on and off depending on whether or not there is a CW. But you can flip it to "on" even without a CW.
Note that the Mastodon API does not allow the reverse scenario (a content warning but a non-sensitive media).
> feat: mark media as sensitive without a CW

- src/routes/_components/compose/ComposeAuthor.html
- src/routes/_components/status/StatusSidebar.html
These elements are duplicated information (the link and name are right next to them), so they should be hidden from screenreaders and tab order.
I also went ahead and fixed a place where I think I should be using aria-busy instead of aria-hidden, because it's content that's asynchronously loading.
> fix: remove avatars from tab order / screenreaders

- CONTRIBUTING.md
- bin/build-inline-script.js
- package.json
- src/routes/_actions/timeline.js
- src/routes/_api/timelines.js
- src/routes/_components/NavShortcuts.html
- src/routes/_components/SvgIconLegacy.html
- src/routes/_components/dialog/components/MediaAltEditor.html
- src/routes/_store/store.js
- src/routes/_utils/asyncPolyfills.js
- src/routes/_utils/loadPolyfills.js
- webpack/client.config.js
- webpack/legacyBabel.config.js
- webpack/server.config.js
- webpack/service-worker.config.js
- webpack/shared.config.js
- yarn.lock
As an experiment (which I may eventually roll back), I would like to try to get Pinafore to run on KaiOS feature phones. Since KaiOS is roughly equivalent to Firefox 48, it doesn't have all the latest browser features. So I would like to have a special mode where I can build Pinafore for "legacy" browsers.
This adds:
LEGACY=1 yarn build
...which will output Pinafore in ES5 format with an extra polyfill (`Intl`) and some extra optimizations. Based on my testing so far, this should allow Pinafore to run on KaiOS phones (although it needs a lot more work to support the small screen size).
I also added some `console.log`s that I find useful for debugging.
> feat: add legacy build

- src/routes/_components/NavShortcuts.html
- src/routes/_components/ShortcutHelpInfo.html
Visually the sticky-positioned "toot" button looks like it might be the 7th nav button, so it makes sense to add a keyboard shortcut for "7". In addition, this improves access to the modal on KaiOS which cannot easily input a "c" character.
> feat: press "7" to open compose modal

- src/routes/_actions/followRequests.js
if you refresh the community page, the verifyCredentials may be null
> fix: fix null exception on community page

- CONTRIBUTING.md
- bin/build-inline-script.js
- webpack/client.config.js
- webpack/service-worker.config.js
- webpack/terser.config.js
Sometimes I find it useful to debug in production mode. This adds
DEBUG=1 yarn build
which can be used to disable minification during a production build.
> feat: add debug build

- src/routes/_actions/addInstance.js
Based on my testing, adding a delay here *may* fix the Safari issue. It seems to be some sort of timing problem, where the localStorage ends up being empty after we navigate back from the target Mastodon instance. I'm hoping that adding a 200ms delay will fix it.
> fix: attempt to fix Safari login bug

- src/routes/_components/compose/ComposeInput.html
After some testing on NVDA on Windows on Chrome/Firefox/FirefoxDeveloperEdition and on VoiceOver on Safari macOS, I believe this is the best implementation.
This changes the code so that we don't set `aria-activedescendant` or `aria-owns` until autocomplete results are available. We remove and add the `aria-activedescendant` and `aria-owns` attributes as the autocomplete results appear and disappear. This should make is so that the `aria-hidden` element which is referenced by `aria-activedescendant`/`aria-owns` is not referenced until it's no longer `aria-hidden`.
@marcozehe I don't think I could reproduce the exact issue you describe in NVDA on Firefox Developer Edition, but I believe this fix is an improvement in VoiceOver on Safari at least. The best screenreader seems to be NVDA on …
> fix: don't set aria-activedescendant immediately on autocomplete textarea

- src/routes/_components/NavItem.html
this broke the navigation animation, so let's remove it for now
> fix: remove focus-after class on nav items

- src/routes/_components/NavItem.html
- src/scss/focus.scss
- src/scss/variables.scss
Improves the appearance of the focus selector on the nav links without disrupting the nav indicator animation.
I realized while writing this that the whole problem I've been having with focus outlines is due to not setting `box-sizing:border-box` on everything. I should really switch to that system, but then I'd have to go back and painstakingly fix every part of the UI where I stupidly hardcoded something down to the pixel. So I just added a TODO.
> fix: improve nav button focus appearance

- src/routes/_components/compose/ComposeAutosuggest.html
After some testing and based on [this suggestion](https://toot.cafe/@marcozehe/102840228729195138) from @MarcoZehe, I think we should just remove the `aria-live` region from the autosuggest. It always felt hacky to me anyway.
I got the original idea from [this implementation](https://haltersweb.github.io/Accessibility/autocomplete.html), but I wonder if it's outdated or wrong. My current implementation seems to cause double utterances in Firefox and some weird garbled text (letter artifacts) as well.
With this new implementation, the results are _perfect_ in Firefox Developer Edition (v70) using NVDA. All other environments I tested have some bugs, but are usable IMO.
- Safari on macOS with VoiceOver: announces that autocomplete results are available, but doesn't announce the first item …
> fix: remove aria-live region for autosuggest

- src/routes/_components/NavShortcuts.html
- src/routes/_components/ShortcutHelpInfo.html
- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_pages/settings/hotkeys.html
- src/routes/_store/observers/leftRightFocusObservers.js
- src/routes/_store/observers/observers.js
- src/routes/_store/store.js
- src/routes/_utils/runMediumPriorityTask.js
- src/routes/_utils/shortcuts.js
- src/routes/_utils/userAgent.js
- tests/spec/024-shortcuts-navigation.js
- tests/utils.js
This is an important accessibility feature for KaiOS (using left/right to change focus, as described in [my blog post](https://nolanlawson.com/2019/09/22/the-joy-and-challenge-of-developing-for-kaios/)), but it could also potentially be used by anyone who wants this feature.
By default, the left/right arrow keys now change the column (or the media in the media dialog). But with this setting checked, left/right changes the focus instead. On KaiOS, this setting is enabled by default and cannot be changed.
> feat: left/right keys can change columns or focus

- src/routes/_components/NavItem.html
- src/routes/_components/TabSet.html
- src/routes/_components/dialog/components/GenericDialogList.html
- src/routes/_components/dialog/components/ModalDialog.html
- src/routes/_components/settings/SettingsListButton.html
- src/routes/_components/status/Media.html
- src/routes/_components/status/Notification.html
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusPoll.html
- src/scss/focus.scss
I still feel that our focus styles are hacky (mostly due to lack of `box-sizing:border-box`, but it's slightly better to use `outline` rather than an extra pseudo-element with a `border`, since the latter can cause re-layouts.
On KaiOS I have to go to extreme lengths to make the focus styles more visible, for whatever reason.
> fix: improve focus styles

- src/routes/_components/status/StatusRelativeDate.html
> fix: remove relative timestamp from tab focus order

- src/routes/_components/AutoplayVideo.html
- src/routes/_components/dialog/components/MediaInDialog.html
iOS Safari shows a broken video player unless you add `type="*"`, web development is really fun sometimes
> fix: fix video on iOS Safari

- src/routes/_components/NavItem.html
- src/routes/_components/compose/LazyComposeBox.html
- src/routes/_components/timeline/LazyTimeline.html
- src/routes/_store/computations/autosuggestComputations.js
- src/routes/_store/computations/computations.js
- src/routes/_store/computations/instanceComputations.js
- src/routes/_store/computations/loggedInComputations.js
- src/routes/_store/computations/navComputations.js
- src/routes/_store/computations/timelineComputations.js
- src/routes/_store/loggedInObserversAndComputations.js
- src/routes/_store/loggedInStoreExtensions.js
- src/routes/_store/mixins/composeMixins.js
- src/routes/_store/mixins/instanceMixins.js
- src/routes/_store/mixins/loggedInMixins.js
- src/routes/_store/mixins/mixins.js
- src/routes/_store/observers/loggedInObservers.js
- src/routes/_store/observers/setupLoggedInObservers.js
- src/routes/_store/store.js
- src/routes/_utils/asyncModules.js
- src/routes/share.html
I thought it might be neat to try to lazy-load store computations we don't need until you're logged in. It turns out that it only saves ~2KB of JS gzipped (~4KB non-gzipped), and on 6x slowdown maybe reduces one of the tasks from ~40ms to ~15ms. Really seems not worth it, but I'm curious if it even passes the tests.
> perf: lazy-load computations (experimental)

- src/routes/_components/status/StatusToolbar.html
- tests/spec/011-reblog-favorites-count.js
Just wanted to float this idea past you maintainers.
I saw a filled-in star on a toot, but I couldn't figure out whether I had already favorited it or not. I hovered over it and saw it said "Favorite", so I thought if I click it then it will favorite the toot. It actually unfavorited it.
So let me know what you think!
I didn't test this yet, btw.
> Add "unfavorite" label.

- src/routes/_api/search.js
- src/routes/_components/search/HashtagSearchResult.html
- src/routes/_utils/ajax.js
fixes #1539
As far as I can tell, this is the only deprecated API we are using. We can try to hit the v2 version and then fall back to the v1 if there's a 404.
> fix: fix search on Mastodon v3

- src/routes/_components/compose/ComposeStickyButton.html
- src/scss/global.scss
I'm not sure what changed, but #667 no longer seems to be an issue, so
it looks like we can safely remove this workaround. I even tested in a
simulator in iOS 11.4 and we don't seem to be affected anymore.
> fix: remove iOS sticky workaround

- src/routes/_components/compose/ComposeBox.html
This fade in animation was not actually working before; now it is.
> fix: fix fade in animation on compose button

- .travis.yml
This thing also seems to break the cache every time. Not sure what it does, but let's just delete it after the script has run.
> chore: delete posix-spawn-benchmark in travis

- src/routes/_api/stream/TimelineStream.js
- src/routes/_database/databaseLifecycle.js
- src/routes/_database/knownInstances.js
- src/routes/_store/LocalStorageStore.js
- src/routes/_utils/asyncModules.js
- src/routes/_utils/lifecycle.js
- src/routes/_utils/scheduleInterval.js
- webpack/client.config.js
- webpack/server.config.js
- webpack/terser.config.js
Also lazy-load page-lifecycle because why not.
This needs some testing, but it seems to work okay. It'd work better if we could enable `runtimeChunk: 'single'` but this breaks Sapper, so we might have to work on that later. (It's a bit sad that the main client.js chunk which is around ~70kB has its cache busted every time due to the Webpack runtime chunk.)
> perf: use webpack contenthash for better caching

- bin/build-now-json.js
- src/service-worker.js
Like sourcemap files, there is no point in proactively caching these
> fix: do not cache license files in service worker

- src/routes/_components/dialog/components/AccountProfileOptionsDialog.html
- src/routes/_components/dialog/components/StatusOptionsDialog.html
Instead of `@foo@bar.com`, just show `@foo`. Partly addresses #1487
> fix: use short usernames in options dialog

- src/routes/_components/AutoplayVideo.html
- src/routes/_components/dialog/components/MediaInDialog.html
I never had any evidence that this actually fixed the iOS video issue (I think #1555 actually fixed it), and I suspect that this may be causing #1590.
> fix: remove type="*" from videos

- package.json
- src/service-worker.js
should fix #1590
#1555 was a targeted fix for Safari, so we should disable it in non-Safari browsers, since it seems to be causing problems.
/cc @sgenoud
> fix: only do range request override in Safari

- src/routes/_utils/runTesseract.js
The last PR broke the tesseract.js progress bar slightly so that it doesn't give immediate feedback. This fixes that.
> fix: fix tesseract.js progress bar

- src/routes/_components/status/StatusCard.html
The `.card-title` element carries `text-overflow: ellipsis`, (and
`white-space: nowrap`), resulting in the last part of long article
titles not being visible. By adding it to the `title` attribute,
one can see the full title on hovering without having to visit the
article first.
The main concern I had was that the text is now technically
duplicated in the source code, and for short titles, also in the
UI. The primary concern there, however, was screen reader users
getting duplicate announcements. However, I believe the `title`
attribute is not announced by screen readers, which this (old)
article seems to confirm:
https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/
That leaves the following two disadvantages:
- This doesn't solve anything for mobile users, who …
> Add the non-truncated text in the title attribute

- src/routes/_components/InformationalFooter.html
- src/routes/_components/NotLoggedInHome.html
- src/routes/_pages/settings/about.html
- src/routes/_pages/settings/instances/add.html
- src/routes/_pages/settings/wellness.html
This removes ~3KB from the main bundle (78.62 -> 75.21) and slightly shrinks the size of some other chunks too. `<ExternalLink>` is ~2.1KB and probably doesn't need to be everywhere in the app since what it does is pretty simple.
I also removed `rel="nofollow"` from the hard-coded external links because really that should only be for user-generated content. I kept `rel="noopener"` for [the security and perf reasons](https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/).
> perf: use raw html for some external links

- bin/build-inline-script.js
- bin/terserOptions.js
- src/routes/_components/dialog/components/MediaDialog.html
- src/routes/_components/shortcut/ScrollListShortcuts.html
- src/routes/_utils/emojiRegex.js
- src/routes/_utils/handleRegex.js
- src/routes/_utils/scrollIntoView.js
- src/routes/_utils/scrollToTop.js
- src/routes/_utils/smoothScroll.js
- src/routes/_utils/testStorage.js
- src/routes/_utils/thunk.js
- src/routes/_utils/urlRegex.js
- src/routes/_utils/userAgent.js
- src/routes/_workers/blurhash.js
- src/service-worker.js
- webpack/terser.config.js
Chrome can take a reeeeaally looooong time to scroll to the top when you're scrolled to the bottom of the timeline. Firefox does not have this problem, and the other browsers don't support native smooth scroll.
We can just use the polyfill in Chrome for this one scenario, since the other ones are fast enough in my experience. I also refactored the userAgent.js code a bit and made sure that, in the worker and service worker files, unnecessary thunks are not included from userAgent.js (i.e. for user agents we never check).
> fix: use smooth scroll polyfill in Chrome for scroll-to-top

- src/client.js
- src/routes/_thirdparty/regenerator-runtime/LICENSE
- src/routes/_thirdparty/regenerator-runtime/runtime.js
- src/routes/_workers/blurhash.js
- webpack/legacyBabel.config.js
- webpack/shared.config.js
For some very strange reason, upgrading tesseract.js (2a248cb) caused legacy mode to start erroring because of some subtlety in how Webpack imports regenerator-runtime. I couldn't for the life of me figure out how to fix it other than directly inlining regenerator-runtime myself.
The error was `TypeError: Cannot set property 'wrap' of undefined`, and searching online found no results, so the easiest was just to fix it manually myself.
This could be because Tesseract imports regenerator-runtime itself; I'm not sure.
> fix: fix regenerator error in legacy mode

- src/routes/_components/NotLoggedInHome.html
- src/routes/_components/settings/SettingsNav.html
- src/routes/_pages/settings/instances/add.html
- src/routes/settings/instances/add.html
I think "log in" is less confusing when you're just getting set up for the first time.
> fix: change "add instance" to "log in" when not logged in

- package.json
- yarn.lock
This makes deployments based on Node 13 easier.
> chore(package): update node-sass to 4.13.0

- src/routes/_thirdparty/unescape/unescape.js
- tests/unit/test-unescape.js
I noticed some cards containing html-encoded apostrophes and smart quotes. We can be better about converting these to plain text.
> fix: fix more html entities in card titles

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_components/compose/ComposeAutosuggestionList.html
- src/routes/_components/compose/ComposeInput.html
- src/routes/_utils/createAutosuggestAccessibleLabel.js
- tests/spec/018-compose-autosuggest.js
some progress on #1629
- works in Chrome on NVDA now
- works in Chrome on VoiceOver now
- shorter aria-labels, don't repeat information like "1 of 3", because it causes the screen reader to speak too frequently, e.g. when the selected result hasn't changed but the number of results has. Also both NVDA and VoiceOver already speak this information.
- stop doing a fancy fade animation, just show and hide the input instantly. I worry it confuses screen readers to have the aria-hidden attribute in there at all. Also it's not really that nice of an animation.
- stop using a single id to identify the active descendant - give immutable IDs and then update the aria-activedescendant instead. I think this is what fixed Chrome.
> fix: improve autosuggest a11y

- src/routes/_components/radio/RadioGroup.html
- src/routes/_components/radio/RadioGroupButton.html
- src/routes/_pages/settings/instances/index.html
- src/routes/_utils/lodash-lite.js
Progress on #1633
This is just s quick sketch of implementing radio buttons for the instance switcher.
One very tricky thing is that the UI is made up of a list where each item has two interactive elements: a link that goes to the instance page, and a button to switch to that instance. It's only the button that should be a radio button, and it's very weird to have links mixed in there.
My current solution is just to wrap the whole thing in a radio group, and then make it so that if any radio button is focused, then you can press up and down to change the radio checked value, as with a standard radio control. But you cannot focus the radio group itself.
Testing in NVDA and VoiceOver, it seems okay. At least it speaks how many items are in the radio group and which one is checked. But I may …
> fix: use radiogroup for instance switcher

- src/routes/_components/IconButton.html
Putting `aria-hidden="false"` everywhere is just extra work and unnecessary. If it's undefined, then Svelte just won't add the attribute at all.
> perf: avoid aria-hidden="false"

- src/routes/_components/compose/ComposeAutosuggest.html
- src/routes/_components/compose/ComposeAutosuggestContainer.html
- src/routes/_components/compose/ComposeBox.html
- src/routes/_components/compose/ComposeInput.html
- src/routes/_components/dialog/components/ModalDialog.html
fixes #1645
Could be broken, needs to be tested in more browsers, but actually this helped clean up the CSS styles quite a bit, because logically it is kind of a globally-absolutely-positioned element.
> fix: make autosuggest list appear over modal dialog

- src/routes/_utils/delegate.js
- src/routes/_utils/eventBus.js
- src/routes/_utils/resize.js
- tests/spec/038-memory-leaks.js
- tests/utils.js
I would love to be able to test DOM listeners too, but it seems too difficult to keep track of these. For now, though, we can at least verify that our synthetic listeners don't leak.
> test: add basic memory leak test

- src/routes/_pages/settings/instances/add.html
On iOS Safari (possibly other browsers as well), auto-capitalization is enabled
even for input fields with inputmode=url.
In my testing, the inputmode attribute itself is supported and working (in so
far that iOS does consider it and provides me a keyboard optimised for URL
inputs, with quick buttons for slash and .com etc).
The autocapitalize is supported on Safari, per:
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize
Fixes https://github.com/nolanlawson/pinafore/issues/1652.
> fix: Avoid autocapitalize keyboard for instance name

- src/routes/_components/search/Search.html
Should fix a reported issue about the search bar not showing up right in the Mastodon-as-a-sidebar Firefox extension.
> fix: fix search width on narrow sizes

- src/scss/custom-scrollbars.scss
These styles have not been supported in Firefox in a long time.
> fix: remove deprecated scrollbar styles

- package.json
- src/routes/_actions/emoji.js
- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_react/createEmojiMartPickerFromData.js
- yarn.lock
We don't actually need it; I can mount and unmount the React component myself and avoid stringifying all the props.
> fix: remove remount

- package.json
- yarn.lock
Because I want to remove the implicit core-js dependency and not wait for an emoji-mart update.
> perf: use emoji-mart fork for now

- src/routes/_components/dialog/components/MediaFocalPointEditor.html
- src/routes/_components/dialog/components/MediaInDialog.html
`intrinsicsize` is no longer on the standards track, but intrinsic width/height is: https://chromestatus.com/feature/5695266130755584
> fix: remove intrinsicsize in favor of width/height

- bin/build-sass.js
(Cherry-picked PR from https://github.com/nolanlawson/pinafore/pull/1694 as it's fairly non-controversial)
> When editing a theme file in vim, a .file.swp file is created and would
> crash the sass compiler. This ignores any hidden files in the directory,
> since they are probably not theme files.
> fix: ignore hidden files in scss/themes

- src/scss/themes/pitchblack.scss
On AMOLED displays the pitch black theme was unsatisfying. I have
changed the theme to use #000 as main theme color, which completely
stops the OLED pixels from emitting light, thus saving energy and
on some devices making the background indistinguishable from the screen
border.
> feat: change pitch black theme

- src/routes/_utils/userAgent/isSafari.js
- src/service-worker.js
fixes #1595
The WebKit bug is marked fixed, and based on my testing it appears to be fixed in iOS 13.3 at least. According to caniuse data, the majority of iOS users are already on 13.3.
I could put in UA-sniffing code in here, but that feels brittle and hard to maintain, so I'd prefer to just remove the workaround entirely.
FYI @sgenoud
> fix: remove safari-specific service worker code

- .travis.yml
Travis recently made `--frozen-lockfile` (or `--pure-lockfile` or whatever) the default, which breaks Greenkeeper. This unbreaks it.
> chore: avoid yarn --pure-lockfile in travis

- src/routes/_components/status/StatusPoll.html
Somehow it is possible to insert newlines into poll options (e.g. this poll posted using tusky): https://mellified.men/@srol/103460845268362583, and Pinafore displays all these newlines as-is, whereas Mastodon collapses them into a single space.
> fix: fix newlines in poll option titles

- src/routes/_components/NavItem.html
fixes #1735
After playing around with Voice Control on iOS 13, it seems that Voice Control really doesn't understand aria-label at all, but it understands text inside of the link just fine. So we can exploit that to just move the text off-screen instead of using `display: none`.
Incidentally, Voice Control also doesn't seem to like small tap targets very much, so it still won't necessarily show the names or numbers when you say "show names" or "show numbers" for all links. But I also tested on a very small phone (iPhone SE first gen), so presumably on a larger phone this would work better. And in any case, this PR at least makes some of the links work correctly, even on a small screen.
Long-term, I assume this is just a bug that Apple will fix. aria-label should be exactly the same as …
> fix: fix nav links in Voice Control on iOS

- src/routes/_components/NavItem.html
- src/routes/_components/NavShortcuts.html
- src/routes/_store/observers/navObservers.js
- src/routes/_utils/normalizePageName.js
- tests/spec/024-shortcuts-navigation.js
fixes #1744
Also fixes it so that the settings nav always shows as selected no matter what settings page you're on
> fix: left/right hotkey works on all settings page

- package.json
- src/routes/_actions/createMakeProps.js
- src/routes/_actions/showMoreAndScrollToTop.js
- src/routes/_components/FocusRestoration.html
- src/routes/_components/virtualList/VirtualListLazyItem.html
- src/routes/_utils/createPriorityQueue.js
- src/routes/_utils/queueMicrotask.js
- src/routes/_utils/tryToFocusElement.js
1. Ensures all statuses are rendered from top to bottom (no more shuffling-card-effect rendering)
2. Wraps all individual status renders in their own requestIdleCallback to improve input responsiveness especially only slow devices like Nexus 5.
I'm still mulling over 2 but 1 is a solid improvement.
> perf: make timeline rendering less janky

- src/routes/_actions/createMakeProps.js
- src/routes/_components/status/Status.html
On the Nexus 5 especially, this ensures we no longer have nearly so many
"long tasks" (i.e. responsiveness is better). It moves html-to-txt
calculation to the same step as blurhash decoding, where it can be done
in requestIdleCallback (heck, maybe someday it could just be done in a
worker thread as well).
> perf: calculate plaintext from HTML content in advance in rIC

- src/routes/_components/virtualList/VirtualListLazyItem.html
After thinking about it, I do not believe the scrollbar is that distracting. But for prefers-reduced-motion we should be careful about the scrollbar growing so quickly.
> fix: only avoid scrollbar motion for prefers-reduced-motion

- src/routes/_components/virtualList/VirtualListItem.html
I noticed that, on 6x CPU throttling in Chrome, the status fade-in animations were not consistent when switching columns. This fixes that using rAF.
> fix: fix fade animations on slow devices

- src/routes/_components/virtualList/VirtualListLazyItem.html
Firefox 68 for Android has a bug where the statuses render in the wrong order if you use async/await instead of Promises. Using Promises fixes it.
> fix: fix rendering order bug in Firefox for Android

- package.json
- yarn.lock
This vuln doesn't really affect us sync we use `sapper export` to build static files (rather than actually running Sapper on the server side), but we may as well fix it.
Sadly had to fix via cherry-pick because latest Sapper is incompatible with Svelte v2. https://github.com/nolanlawson/sapper/commit/99798006c3a00b9f95ede212f844c75ee7cf1bb0
> update sapper to fix SNYK-JS-SAPPER-561051

- bin/build-now-json.js
Improves the CSP a bit, following advice from Mozilla Observatory.
- `default-src` is `'none'`
- restrict `form-action` and `frame-ancestors`
- restrict `img-src` and `media-src` to just what we need
Pinafore doesn't need to run in an iframe, and it does need to send XHRs and img/audio/video requests to arbitrary origins, but most stuff we can just block
> fix: beef up CSP headers

- src/routes/_components/compose/ComposeStickyButton.html
fixes #1681
There's apparently an intersection observer bug in Firefox 68 on Android that causes the Toot button to appear as "sticky" even though it's inside the dialog and therefore can never go into the "sticky" state.
The simplest approach is to just never create the intersection observers in the first place if the button can never become sticky. Not sure why I never did this in the first place; there are plenty of never-gonna-be-sticky buttons and there's no point in running the sticky logic for them.
> fix: fix delete-and-redraft in Firefox Android

- src/routes/_components/list/ListItem.html
Pulling out a CSS/animation change in #1769 that isn't directly related to that PR, and which we would like to have regardless (it applies if a status is received asynchronously and appears in the thread, it will need to fade in).
> fix: ListItem should have proper fade animations

- package.json
- src/build/template.html
- src/routes/_pages/settings/general.html
- src/routes/_store/observers/focusRingObservers.js
- src/routes/_store/observers/observers.js
- src/routes/_store/store.js
- src/routes/_utils/asyncPolyfills.js
- src/routes/_utils/loadPolyfills.js
- src/routes/_utils/supportsSelector.js
- src/scss/focus.scss
- yarn.lock
Uses the [`:focus-visible` polyfill](https://github.com/WICG/focus-visible) to disable the focus ring when using mouse/touch interaction as opposed to keyboard interaction. This follows a pretty common pattern across webapps, where the focus ring is only shown when the user is detected to be a keyboard user.
The standard is currently not implemented in any browser, except Chrome with "experimental web platform features" enabled. But if it's never implemented, we can just keep using the polyfill.
I also added a setting to always show the focus ring, disabled by default. I disabled it by default because my hunch is that 1) the average mouse user does not know what a focus ring is and can't be bothered to go into their settings to change things, whereas 2) keyboard users are more likely to …
> feat: use :focus-visible, add setting to enable/disable it

- src/routes/_utils/userAgent/isChromePre82.js
- src/routes/_workers/blurhash.js
Chrome fixed this bug (https://bugs.chromium.org/p/chromium/issues/detail?id=1053477), so we can re-enable it for Chrome 82+
> perf: use OffscreenCanvas in Chrome 82+

- src/client.js
- src/routes/_utils/asyncPolyfills.js
- src/routes/_utils/loadPolyfills.js
- src/routes/_utils/supportsSelector.js
This reverts commit c98b198e60338b34a9e2cc592c80814fd83455a6.
#1783
It seems like Chrome is likely to ship this soon, it's in the CSS spec, and I don't want to have to jump through a lot of hoops to re-enable it. Also the perf hit doesn't seem that bad, not even sure I can measure it. Let's just keep things simple
> fix: Revert "perf: always load focus-visible polyfill (#1780)"

- src/client.js
- src/routes/_utils/loadNonCriticalPolyfills.js
- src/routes/_utils/loadPolyfills.js
I think this is a more reasonable version of #1780. The `:focus-visible` polyfill is not really a critical polyfill, so we can just lazy-load it after the main app has loaded.
> perf: lazy-lazy-load the :focus-visible polyfill

- src/routes/_components/Nav.html
- src/routes/_components/NavItem.html
- src/routes/_components/NavItemIcon.html
- src/routes/_components/compose/ComposeButton.html
- src/routes/_components/compose/ComposeStickyButton.html
- src/routes/_components/list/List.html
- src/scss/global.scss
- src/scss/variables.scss
The way the height of the nav bar is calculated (and how that affects the sticky-positioned button and scroll-into-view on lists) was kind of messed up and hard to tweak. It was a lot of manual calculations that are better done in explicit `calc()`s so they can be more precise.
This isn't pixel-perfect exactly like the old design, but it's closer to what I had in mind, and should be easier to maintain.
> fix: css cleanup of nav-related variables

- src/routes/_components/dialog/components/EmojiDialog.html
This still needs some work, but it's better than before. The picker should resize even when the keyboard is open
> fix: emoji picker height on mobile

- src/routes/_components/dialog/components/EmojiDialog.html
When searching, the emoji picker changes height on mobile, which we don't want
> fix: fix mobile size of picker when searching

- src/routes/_utils/createAutosuggestAccessibleLabel.js
Put the native emoji shortcodes into the accessible label
> fix: improve a11y of autosuggest labels

- src/routes/_components/NavShortcuts.html
- tests/spec/024-shortcuts-navigation.js
`/` is a well-known vi/vim key-binding for search. It is supported by
Firefox for a 'quick find' feature in addition to the main find feature
available with the Ctrl+F key combination. [DuckDuckGo](https://duckduckgo.com) also supports the
key to focus the search bar as well. Other websites like GMail also
focuses the search bar on pressing the `/`. It is not only DuckDuckGo or
GMail alone that supports the key. I've noticed it on multiple websites
but I can only think of these 2 that are popular enough to argue support
over the top of my head. I cannot say if it is a good practice per se;
but I feel that it is a good feature to support.
> add `/` as a navigation shortcut for search

- package.json
- src/routes/_components/dialog/components/EmojiDialog.html
- yarn.lock
v1.1.0 of emoji-picker-element allows for the attribute format for some properties, so let's use it.
> chore: update emoji-picker-element, use declarative format

- src/routes/_actions/bookmark.js
- src/routes/_components/dialog/components/StatusOptionsDialog.html
For consistency with the rest of the UI, say "toot" instead of "status" and specify "toot."
> fix: tweak language around bookmarking

- src/routes/_components/virtualList/VirtualListItem.html
This fixes an issue in Firefox (on Ubuntu anyway) where it doesn't always draw the border between virtual list items. Also in terms of performance it should be roughly the same; my quick testing doesn't uncover any big difference in perf between the two, at least according to Chrome. We're not animating the property, so I don't think we need to use `transform`.
Before and after in Firefox:
> fix: use absolute positioning over transform

- src/routes/_actions/timeline.js
- src/routes/_components/virtualList/VirtualList.html
- tests/serverActions.js
- tests/spec/039-empty-list.js
- tests/spec/136-empty-list.js
- tests/utils.js
Instead, they now show "Nothing to show." I only fixed this for VirtualList because List should never be empty (threads).
Fixes #1763
> fix: empty timelines no longer show infinite loading spinner

- src/routes/_store/computations/navComputations.js
Pinning the bookmarks page would accidentally pin the local timeline page due a forgotten `else if`. :heart:
Fixes #1858
> fix: pinning the bookmarks page

- src/routes/_pages/community/index.html
- src/routes/_pages/search.html
This probably really doesn't matter, as it's an extreme edge case (only occurs if you're on the bookmarks page, on a browser that doesn't support Service Worker or doesn't have Service Worker enabled for whatever reason, and you refresh), but it seems worth covering.
> fix: ensure bookmarks page has generated HTML file

- src/routes/_components/dialog/components/EmojiDialog.html
- src/routes/_utils/loadNonCriticalPolyfills.js
- src/routes/_utils/supportsFocusVisible.js
Chrome beta actually supports `:focus-visible` now, so there's no reason to statically load the polyfill in the emoji picker.
> fix: dynamically import focus-visible polyfill for emoji picker

- bin/build-vercel-json.js
- src/service-worker.js
Somehow some `.LICENSE.txt` files ended up in the Service Worker cache; we definitely don't need those.
> fix: remove license files from service worker

- src/scss/themes/dark-grayscale.scss
The pressed state, such as used for the "Unfollow" button, was effectively identical to the background, thus making it invisible.
Brighten it up to fix this. The relative differences are kept the same as before and match the default theme,, e.g. the brightness ranges from (darkest) Unfollow > Unfollow-hover > Follow > Follow-hover (brightest)
| | Before | After
|--|--|--
| Follow | <img width="216" alt="before-follow" src="https://user-images.githubusercontent.com/156867/97092797-d27b2000-163e-11eb-99ac-a1539a5c371e.png"> | <img width="208" alt="after-follow" src="https://user-images.githubusercontent.com/156867/97092799-d444e380-163e-11eb-9605-029754d55713.png">
| Unfollow | <img width="209" alt="before-unfollow" src="https://user-images.githubusercontent.com/156867/97092798-d3ac4d00-163e …
> fix: change dark grayscale to use have a brighter action-button color

- src/routes/_components/IconButton.html
- src/routes/_components/status/StatusToolbar.html
fixes #1884
If "disable entire toot area" is on, then the cursor becomes default between the buttons, and clicking does nothing. If it is off (default), then the cursor is always pointer and clicking between the buttons clicks the whole toot.
> fix: fix tappable area between toolbar buttons

- bin/clone-mastodon.js
- bin/run-mastodon.js
Also do a more efficient checkout of the Mastodon tag from git
> chore: cache bundler correctly in CircleCI

- src/routes/_actions/compose.js
- src/routes/_actions/media.js
- src/routes/_components/dialog/components/MediaAltEditor.html
- src/routes/_database/knownInstances.js
- src/routes/_thirdparty/idb-keyval/idb-keyval.js
- src/routes/_utils/mediaUploadFileCache.js
- tests/unit/test-media-cache.js
fixes #1901
Notably also fixes it in such a way that we can keep `no-referrer` for the privacy benefits #1877
An added benefit is that we no longer care what CORS headers the Mastodon instance may set for its media files.
> fix: fix tainted canvas error with OCR

- webpack/shared.config.js
This module is taking up space and it's behind an `else` block that's never executed.
> perf: remove lookup-closest-locale

- src/routes/_thirdparty/a11y-dialog/a11y-dialog.js
`<video controls>` and `<audio controls>` aren't 100% fixable inside of a modal dialog (see https://nolanlawson.com/2021/02/13/managing-focus-in-the-shadow-dom/ for more details), but we can at least focus the video/audio element while you tab around inside of the dialog.
The only way right now to completely fix this is to use a non-native video/audio player, but I don't want to take the perf and complexity hit of including some third-party control here.
> fix: partially fix video/audio in dialogs

- bin/run-mastodon.js
This fixes some bugs in dev mode where the Mastodon DB might say it needs a Rails migration stil.
> test: always migrate mastodon server when launching

- package.json
- src/routes/_utils/asyncPolyfills.js
- src/routes/_utils/loadPolyfills.js
- src/routes/_utils/relativeTimeFormatPolyfill.js
- webpack/shared.config.js
- yarn.lock
Fixes #1938
This adds a lot of extra polyfills (128kB! It's our second-biggest chunk!) just for iOS 13, which doesn't make me happy. But on the bright side, these polyfills are conditionally loaded. (Sadly, though, the Service Worker still downloads and caches them for all browsers.)
When iOS 13 is less widespread, we can remove this.
Chunk map, notice it's the second-biggest: >_<
> fix: fix Intl.RelativeTimeFormat on iOS 13

- src/service-worker.js
- webpack/client.config.js
This used to not work because Vercel didn't allow URLs with `$` in them. Now I want it back because #1947 added a fairly large polyfill only needed for iOS 13 and below. Let's see if Vercel has fixed this bug yet.
> perf: cache polyfills on-demand

- src/routes/_components/dialog/components/EmojiDialog.html
Just makes the padding a bit better on large mobile phone sizes, I felt it was getting too cramped
> fix: tweak emoji picker style on mobile

- package.json
- yarn.lock
Maintaining this old Sapper fork is not fun, but here I am
> chore: update sapper to actually fix webpack 5

- src/intl/de.js
- src/intl/en-US.js
- src/intl/fr.js
- src/routes/_components/shortcut/ScrollListShortcuts.html
- src/routes/_components/status/StatusSpoiler.html
- tests/serverActions.js
- tests/spec/137-shortcuts-spoiler.js
Fixes #1914
Adds a keyboard shortcut, `z`, to open or close all content warnings in a thread. `z` was chosen because of its proximity to `x` on a US keyboard, and because Mastodon doesn't seem to have a shortcut for this, or to use `z` for something else.
This isn't accessible to non-keyboard users, but I consider this a power user feature, and I'm hesitant to clutter up the UI with more buttons, so I consider #1914 closed after this is merged.
> feat: implement shortcut for opening/closing all CWs

- src/intl/de.js
This adjusts the help text to be more explicit about the purpose of the z shortcut key.
> Adjust German help text for Expand All CWs

- src/routes/_components/shortcut/ScrollListShortcuts.html
Follows-up 4218c4ce640ab33897733b4858d5c60676b4a5aa.
When accessing the IDL property, values tend to be reflected in a normalised
type and form. In the case of HTMLInputElement.type, this means the
returned value is always one of the supported and canonical lowercase
values regardless of what value the corresponding attribute holds, or
even if the attribute doesn't exist (the default will still be "text").
> chore: clean up input.type property access

- src/routes/_utils/tesseractWorker.js
- webpack/server.config.js
Reduces total webpack JS size from 1.2 MB to 1.19 MB
> perf: reduce tesseract bundle size by directly importing createWorker

- src/routes/_pages/index.html
- src/routes/_store/observers/loggedInObservers.js
- src/routes/_store/observers/showShareDialogObservers.js
Saves us one JS request on a normal non-logged-in home page load
> perf: avoid importing the DB for non-logged-in users

- src/routes/_utils/supportsFocusVisible.js
- src/routes/_utils/userAgent/isFirefox.js
I'm sufficiently annoyed by [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1699154) that I'm willing to use the `:focus-visible` polyfill rather than Firefox's native implementation. It even triggers focus rings on mobile, which is too jarring IMO.
Testing WebKit nightly, it does not appear to have the same bug.
> fix: disable :focus-visible on Firefox

- src/service-worker.js
I'm using this (for now) as a signal that we're running in a PWA, so let's keep it consistent.
> fix: add pwa=true query param when sharing files

- src/intl/en-US.js
- src/routes/_components/status/StatusRelativeDate.html
- src/routes/_pages/settings/wellness.html
- src/routes/_store/store.js
Relative timestamps can cause you to feel that things are especially
interesting because they are happening "right now"; the effect is
lessened if you see absolute timestamps instead.
This fixes #2011
As it stands, this PR has a couple of issues that still need to be solved:
When absolute timestamps are enabled, I intended to remove the `title` attribute on the timestamps, as they're no longer needed. [According to the svelte docs](https://v2.svelte.dev/guide#tags), attributes are supposed to be removed from the element if their value is `undefined` or `null`, but instead the `title` attribute is getting set to the literal string `undefined`.
The wording of the option name is a bit too long, and wraps. I'm unsure about the option group heading that I've chosen in the settings panel.
> Add a Wellness option to show absolute timestamps instead of relative

- src/intl/en-US.js
- src/routes/_a11y/getAccessibleLabelForStatus.js
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusRelativeDate.html
- src/routes/_utils/formatters.js
- tests/spec/041-wellness.js
- tests/utils.js
Tweaks to #2014 based on https://github.com/nolanlawson/pinafore/pull/2014#issuecomment-803632490.
- Shows only the month/day/year, not the time (when this wellness setting is activated)
- Moves logic into Status.html so we can also adjust the aria-label. Presumably users of screen readers who enable this setting will also not want to see the relative timestamp.
This fits better on small screens IMO:
/cc @kepstin
> fix: use day-only time format for wellness setting 

- bin/clone-mastodon.js
CI is failing due to this fun situation: https://github.com/tootsuite/mastodon/issues/15986
> chore: update tested mastodon to fix mimemagic

- src/routes/_components/status/StatusRelativeDate.html
- tests/spec/022-status-aria-label.js
- tests/utils.js
This regressed due to #2014. Added a test to ensure it doesn't regress again.
> fix: fix aria-labels on relative timestamps

- src/routes/_components/MediaControlsFix.html
- src/routes/_components/dialog/components/MediaInDialog.html
- src/routes/_thirdparty/a11y-dialog/a11y-dialog.js
- src/routes/_utils/events.js
This is a hack that mostly makes audio/video controls in a dialog work properly accessibility-wise. You can now Tab through the shadow elements and focus wraps within the dialog properly.
It works in Firefox and Chrome, but in Safari the focus cannot cycle backwards from the first element inside the dialog. I'm not sure how to fix Safari, so I'm just not going to bother with it for now.
Also there are some other things that are impossible to fix using video/audio controls, which are noted in the comments. But this is still better than the status quo, which wouldn't allow you to Tab inside the video/audio controls at all.
> fix: fix a11y for audio/video controls in dialog

- src/routes/_utils/supportsFocusVisible.js
- src/routes/_utils/userAgent/isFirefox.js
- src/routes/_utils/userAgent/isFirefoxPre88.js
https://github.com/nolanlawson/pinafore/issues/2038 made me realize Firefox has shipped this fix, so we can use native focus-visible now. https://bugzilla.mozilla.org/show_bug.cgi?id=1699154
> fix: switch to native :focus-visible for firefox 88+

- src/client.js
- src/routes/_utils/idbReady.js
see https://github.com/jakearchibald/safari-14-idb-fix/pull/2
> fix: work around missing indexedDB.databases

- bin/build-template-html.js
- package.json
- yarn.lock
Probably a breaking change for self-hosters because we'll have to bump the minimum required Node version to whichever versions support `perf_hooks`.
> fix: remove performance-now module, use perf_hooks

- src/routes/_utils/supportsFocusVisible.js
- src/routes/_utils/userAgent/isFirefox.js
- src/routes/_utils/userAgent/isFirefoxPre90.js
`:focus-visible` bugs are fixed in Firefox 90
> fix: enable focus-visible in Firefox 90

- src/build/template.html
Fixes #2104
I haven't actually tested this, but `white` isn't even documented on Apple's documentation, so I'm guessing at some point it worked but doesn't work anymore in recent iOS versions. I have no idea. https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html
> fix(ios): change status-bar-style to default

- src/routes/_api/media.js
Fixes #2078. Falls back to v1 if v2 is unavailable.
There doesn't seem to be any breakage. I don't think we were using the `url` from the v1 API.
> fix: use /api/v2/media

- src/build/template.html
I don't think the change made to the status bar in #2108 is quite right. The status bar now has a translucent background when I test in iOS 15 on an iPod Touch. The timeline content bleeds through, which looks really weird.
I think this should be switched back until we figure out what magic string iOS wants.
> fix: make ios status bar default color again

- Dockerfile
The `node:alpine` Docker image appears to have recently been updated to point to Node 17, breaking new builds of Pinafore. This commit explicitly specifies Node 16 until the underlying reason for the build failure on 17+ can be fixed.
I've verified this builds successfully on my own servers.
> Dockerfile: Use explicit node version

- src/routes/_components/status/StatusPoll.html
Misskey reports `voters_cont` as null, so just use the `votes_count` in that case.
The percentages won't be as a percent of the number of voters – instead it'll be as a percent of the number of individual votes. But this is fine. Maybe Misskey only does this for non-multiple-choice polls.
The poll looks like this in Misskey:
```js
"poll": {
"id": "96327",
"expires_at": "2022-05-08T08:26:05.336Z",
"expired": false,
"multiple": false,
"votes_count": 123,
"voters_count": null,
"voted": false,
"own_votes": [],
"options": [
/* ... */
],
"emojis": []
}
}
```
> fix: fix votes count on Misskey polls

- src/routes/_thirdparty/websocket/websocket.js
Heya! I was running into a bug using Pinafore with GoToSocial, but only under Chrome.
Specifically, was getting the following error:
`Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`
I looked at the request headers that were being sent by the websocket connection, and saw 'Sec-Websocket-Protocol: null`.
After a bit of digging through the code, I noticed that if you pass 'null' to the WebSocket client constructor, it will pass 'null' via the headers, whereas if you just pass an empty array by default, this header is skipped.
This seems to resolve the issue :) Tested with Chrome and GtS
> fix: use empty array for ws protocols instead of null

- src/intl/en-US.js
- src/routes/_components/status/Notification.html
- src/routes/_components/status/StatusHeader.html
- src/service-worker.js
This only matters for instance admins, but there's apparently a notification when new users sign up. I'm not going to bother adding filters for these, but we can at least fix the text so it doesn't say "followed you."
> fix: show proper text for signup notifications

- package.json
- yarn.lock
Doesn't seem like these new updates should break us
> chore: update formatjs deps

- bin/restore-mastodon-data.js
Managed to repro the flaky notifications test; it turns out that Mastodon randomly changes the order on some of these notifications. Hoping that changing the restore delays fixes this.
Spot the difference in these two timelines (last three notifications):
> chore: attempt to fix flaky test

- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusPoll.html
Subtle bug: when voting on a poll, the status height may change after you vote, so the virtual list sizes have to be recalculated.
> fix: recalculate toot height after voting on poll

- src/routes/_components/dialog/components/EmojiDialog.html
Not sure when this broke, but it wasn't inserting emoji correctly with skintones. Fixed
> fix: fix inserting emoji with skintone

- src/build/template.html
- src/routes/_components/snackbar/Snackbar.html
- src/routes/_components/toast/Toast.html
- src/scss/variables.scss
When the nav is on the bottom (#2164), the toast and snackbar obscure it (or are not positioned properly relative to it). Dumb oversight I made. This fixes it.
> fix: fix position of toast/snackbar for bottom nav

- src/routes/_components/shortcut/ScrollListShortcuts.html
Previously, if focus was on an element inside a toot instead of the toot itself (e.g. moving to a toot and pressing tab), keyboard commands acted as if no toot was active. In particular, this meant that the arrow keys scrolled to the first visible toot.
Fixes #2228.
> fix: If the focus is inside a toot, make keyboard commands operate relative to the parent toot.

- src/routes/_components/compose/ComposeInput.html
- src/routes/_thirdparty/a11y-dialog/a11y-dialog.js
ComposeBox already specified autoFocus for the ComposeInput. However, this didn't work because the dialog was disabled when the ComposeInput code tried to focus the textarea. To fix this, tweak A11yDialog to look for the autofocus attribute when determining what to focus. This is consistent with the behavior for native HTML dialogs. Then, have ComposeInput set this attribute if it's in a dialog. Fixes #1839.
> fix: Focus the textarea in the Compose dialog instead of the Close button.

- src/routes/_components/timeline/LoadingFooter.html
Fixes "Loading more" alert creates extraneous verbosity for screen reader users #2226.#2226
> Remove alert role from the loading indicator so it no longer interferes with screen readers.

- src/routes/_components/IconButton.html
- src/routes/_components/status/StatusToolbar.html
- src/routes/_static/animations.js
- tests/spec/007-account-profile.js
By changing the shape it means no matter what the colour difference between pressed and non-pressed it'll be possible to know the state.
I tried having it appear after the animation and it felt nicer before but let me know what you think when you try it out.
> fix: dont rely on colour for boost/favourite state

- src/routes/_components/timeline/LoadingFooter.html
This implements @jcsteh's suggestion here: https://github.com/nolanlawson/pinafore/issues/2226#issuecomment-1325805513
It announces "Loading more" after a 1 second delay, if the new statuses at the bottom of the timeline are delayed.
> fix: announce "loading more" with aria-live=polite after delay

- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
If your OS is in dark mode but the theme is light, then the radio buttons might look dark when they should be light, or vice versa. At least in Firefox. This fixes that.
> fix: fix mismatched dark/light color-scheme

- src/routes/_components/IconButton.html
Just a small aesthetic change to make them feel more connected.
| Before | After |
| - | - |
| ![](https://user-images.githubusercontent.com/2445413/203971277-d52edcf7-d350-4847-931c-9d7ae6238b90.png) | ![](https://user-images.githubusercontent.com/2445413/203971070-f1ba6bb6-222c-4275-b2cb-da00853db140.png) |
> fix: bring check closer to icon

- src/routes/_components/status/StatusContent.html
- src/scss/global.scss
Some other parts of the interface for example URLs in profiles use the invisible class, move this to the top level global file so it'll be applied everywhere.
| Before | After |
| - | - |
| ![](https://user-images.githubusercontent.com/2445413/204026358-985b61a5-1dc1-4fda-8297-25633ad0c5b7.png) | ![](https://user-images.githubusercontent.com/2445413/204026412-d2521e8f-0933-4b17-baa7-8003b374ae6e.png) |
> fix: hide invisible content consistently

- src/routes/_components/status/StatusHeader.html
- tests/spec/010-focus.js
- tests/utils.js
This change makes clicking on the small sized avatar go to the account page for the reposter, previously small and large images both linked to the original poster's account page
> Make click on reposter's small avatar image go to reposter's account page

- src/routes/_a11y/getAccessibleLabelForStatus.js
- src/routes/_components/status/Status.html
- tests/spec/022-status-aria-label.js
- tests/spec/120-status-aria-label.js
> feat: Allow image descriptions to be read automatically by screen readers without needing to expand media.

- src/intl/en-US.js
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusToolbar.html
- src/routes/_utils/shortcuts.js
- src/routes/_utils/tryToFocusElement.js
- tests/spec/025-shortcuts-status.js
> feat: Make it possible to close inline reply with the escape key.

- src/intl/en-US.js
Generally phrasing that talks about "the disabled" or "the visually impaired" feels othering, whereas it is more common these days to have identity focused framing.
> fix: improve wording of disabled identity

- src/scss/themes/_base.scss
- src/scss/variables.scss
Make the background of selected navigation items darker so it is easier to read with white text (this meets WCAG contrast requirements).
Make the indicator bar more prominent to make it clearer which item is selected now that the background is done less to indicate this.
> Improve navigation readability

- src/intl/en-US.js
- src/routes/_components/status/StatusToolbar.html
> feat: Add "a" keyboard shortcut to bookmark a toot.

- src/routes/_components/NavItem.html
- src/scss/themes/_base.scss
- src/scss/themes/cobalt.scss
- src/scss/themes/dark-grayscale.scss
- src/scss/themes/hacker.scss
- src/scss/themes/punk.scss
- src/scss/themes/riot.scss
Fixes #2290.
https://user-images.githubusercontent.com/283842/205460527-0c795d55-436b-49c2-8606-b2821ff7cbd7.mp4
My solution was a few things:
1. Instead of using colors with transparency (which I found impossible to animate correctly due to backgrounds messing with the foreground color), use SASS `mix()` to achieve basically the same colors. (I eyeballed it, so not super scientific, but it seems close.)
2. When animating the indicator, mutate the color of the wrapper around (behind) it
3. Refactor the CSS vars to make the code easier to understand (`--nav-indicator-bg`, `--nav-indicator-bg-active`, `--nav-indicator-bg-hover`).
I tested 3 methods: using the keyboard to change the page, using the mouse on desktop, and simulating touch on a mobile phone. They all look pretty good to me.
FYI …
> fix: fix nav animations

- src/intl/en-US.js
- src/routes/_a11y/getAccessibleLabelForStatus.js
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusHeader.html
Fixes #2280
I looked at "Inspect accessibility properties" in Firefox DevTools and the accessibility label looks right, similar to that for a boost notification.
Of course, these new strings aren't internationalized, as I'm not fluent in the relevant languages; let me know if there's anything you recommend I do about that.
> fix: correctly label toot edited notification

- bin/svgs.js
- src/routes/_components/DynamicPageBanner.html
Depending on the operating system and therefore the system font the back icon being a unicode arrow means it'll render inconsistently, sometimes I've seen it looking really odd.
Instead make use of the font awesome arrow so that'll it render consistently no matter the system font.
| Before | After |
| - | - |
| ![Slender back arrow before button label](https://user-images.githubusercontent.com/2445413/205987743-c601ec47-f40c-4918-bd83-b7727f883265.png) | ![Thicker font awesome back arrow before button label](https://user-images.githubusercontent.com/2445413/205987759-d96633a1-913a-4aff-8572-3360413eef0d.png) |
> fix: back button icon rendering inconsistently

- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusPoll.html
- src/scss/themes/_base.scss
- src/scss/themes/_dark.scss
- tests/spec/005-status-types.js
- tests/spec/026-shortcuts-notification.js
Use lowest possible contrast gray that meets WCAG requirements for very deemphasised text.
Removes the status toolbar when its a notification for your own toot
Makes the notification page more readable without compromising access as much.
Closes https://github.com/nolanlawson/pinafore/issues/2249
| Before | After |
| - | - |
| ![notifications page with hard to read text in toot notification](https://user-images.githubusercontent.com/2445413/205767224-be764437-cb58-4d2c-9e52-c7ed3a2bec0f.png) | ![notifications page with clearer text and no buttons in toot notification](https://user-images.githubusercontent.com/2445413/205767233-45345644-5f6d-4378-bde2-30fa7ad81c82.png) |
| Before | After |
| - | - |
| ![notifications page with hard to read text in toot …
> Improve notifications page readability

- src/routes/_actions/stream/processMessage.js
- src/routes/_actions/updateStatus.js
- src/routes/_api/statuses.js
- src/routes/_database/timelines/updateStatus.js
- tests/serverActions.js
- tests/spec/140-editing.js
This is step 1 in implementing editing (#2179). At the very least we can updatt the cache when a status is updated.
> fix: handle status edit events

- src/scss/themes/pitchblack.scss
Increase the contrast of unpressed action buttons so they're easier to see.
This brings the icons to 3:1 contrast while keeping colour in themes.
> Improve icon readability in pitch black theme

- src/scss/themes/_base.scss
Increase the contrast of unpressed action buttons so they're easier to see.
This brings the icons to 3:1 contrast while keeping colour in themes.
> Improve icon readability in light theme

- src/scss/themes/mastodon.scss
- src/scss/themes/ozark.scss
I think this'll be the last of the icon improvements for now...
> Improve icon readability in dark themes

- src/scss/themes/grayscale.scss
- src/scss/themes/majesty.scss
Tweaks the colors on the majesty/grayscale themes. The buttons are still >3.0 contrast ratio.
> fix: lighten button colors on some themes

- bin/build-vercel-json.js
- vercel.json
builds property is not recommended in [project config with vercel.json](https://vercel.com/docs/project-configuration).
Using just buildCommand has been useful when I have host the merged translation into Spanish in Vercel. A fellow has registered a domain where it's available. We use the same vercel.json file, but replacing the builds property with `"buildCommand": "LOCALE=es yarn build"`.
I think that this change may make easier to understand how to host translated versions of Pinafore in Vercel.
I'm very grateful with the person who has registered this domain assuming costs himself for the benefit of the spanish community
See the spanish translation working at
https://pinafore.es
I just hosted it in a free Vercel account.
Thanks
> Replace builds with buildCommand in vercel.json

- docs/Internationalization.md
> Explain how to use the buildCommand for internationalization

- src/routes/_api/oauth.js
- src/routes/_utils/ajax.js
* Token request should use `application/x-www-form-urlencoded`: https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3
> OAuth2: use correct `Content-Type` as specified in RFC

- src/intl/en-US.js
- src/routes/_components/status/Status.html
- src/routes/_components/status/StatusSpoiler.html
- src/routes/_pages/settings/general.html
- src/routes/_store/store.js
- tests/spec/043-content-warnings.js
Added an option to always expand posts marked with content warnings. If the option is enabled, posts with content warnings are expanded by default, but can be closed using the "show less" button as usual.
This adds a new intl key. I wasn't sure whether the correct approach was just to add the key to en_US or to add it (untranslated) to every language; I've just done the former for now, but if it does need to be added untranslated to every language please let me know and I'll do so.
Fixes #1997.
> Add option to always expand posts marked with content warnings

- src/build/template.html
Currently, the grayscale filter does not apply to header images. This PR aims to remediate that by adding the `account-profile` class to the `theGrayscaleStyle` style definitions.
> fix: grayscale mode support for header images
